---
title: "Making topographic variables"
author: "Shane Dewees"
date: "2/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(spatialEco)
library(here)
library(terra)
```

```{r}
elevation <- rast(here("data", "raw_data",  "elevation.tif"))
elevation[elevation < 300] <- NA
heat_load_index <- hli(elevation)
diurnal_heat_index <- dahi(elevation)
topographic_position <- tpi(elevation, win = "circle", scale = 5)
sol_rad_aspect <- trasp(elevation)
terrain_ruggedness <- tri(elevation, s = 7)
saga_wetness <- rast(here("data", "raw_data", "saga_wetness.tif"))
saga_wetness <- ifel(!is.na(elevation), yes = saga_wetness, NA)
twi <- rast(here("data", "raw_data", "twi.tif"))
twi <- ifel(!is.na(elevation), yes = twi, NA)
```


```{r}
writeRaster(elevation, filename = here("data", "clean_data", "elevation.tif"), overwrite = TRUE)
writeRaster(heat_load_index, filename = here("data", "clean_data", "heat_load_index.tif"), overwrite = TRUE)
writeRaster(diurnal_heat_index, filename = here("data", "clean_data", "diurnal_heat.tif"), overwrite = TRUE)
writeRaster(topographic_position, filename = here("data", "clean_data", "topographic_position.tif"), overwrite = TRUE)
writeRaster(sol_rad_aspect, filename = here("data", "clean_data", "sol_rad_aspect.tif"), overwrite = TRUE)
writeRaster(terrain_ruggedness, filename = here("data", "clean_data", "terrain_ruggedness.tif"), overwrite = TRUE)
writeRaster(saga_wetness, filename = here("data", "clean_data", "saga_wetness.tif"), overwrite = TRUE)
writeRaster(twi, filename = here("data", "clean_data", "twi.tif"), overwrite = TRUE)
```



