---
title: "environmental data"
author: "Shane Dewees"
date: "2/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(lubridate)
```

## Soil Moisture

```{r}
soil_moisture_1 <- read.csv(here("data", "raw_data", "soil_moisture_data", "piru landscape TDR data - 1_7.csv")) %>% dplyr::select(plot, m1, m2, m3, m4, date) %>% 
  group_by(plot) %>% 
  mutate(date = mdy("01-07-2020"),
         soil_moisture = mean(c(m1, m2, m3, m4), na.rm = TRUE)) %>% 
  ungroup() %>% 
  dplyr::select(plot, soil_moisture, date)

soil_moisture_2 <- read.csv(here("data", "raw_data", "soil_moisture_data", "piru landscape TDR data - 4_23.csv"))%>% dplyr::select(plot, m1, m2, m3, m4, date) %>% 
  group_by(plot) %>% 
  mutate(date = mdy("04-23-2020"),
         soil_moisture = mean(c(m1, m2, m3, m4), na.rm = TRUE)) %>%
  ungroup() %>% 
  
  dplyr::select(plot, soil_moisture, date)

soil_moisture_3 <- read.csv(here("data", "raw_data", "soil_moisture_data", "piru landscape TDR data - 5_21.csv"))%>% dplyr::select(plot, m1, m2, m3, m4, date) %>% 
  group_by(plot) %>% 
  mutate(date = mdy("05-21-2020"),
         soil_moisture = mean(c(m1, m2, m3, m4), na.rm = TRUE)) %>% 
  ungroup() %>% 
  dplyr::select(plot, soil_moisture, date)

# Moisture of 3 discreet timepoints
soil_moisture <- rbind(soil_moisture_1, soil_moisture_2) %>% 
  rbind(soil_moisture_3) %>% 
  rename(plot_number = plot)

moisture_logger_1 <- read.csv(here("data", "raw_data", "soil_moisture_data", "Data_loggers", "EM12384 22Oct20-1548.csv")) %>% 
  rename(date_time = Measurement.Time) %>% 
  rename("1132" = X1132) %>% 
  rename("1130" = X1130) %>% 
  rename("1124" = X1124) %>% 
  rename("1131" = X1131) %>% 
  rename("1647" = X1647) %>% 
  mutate(date_time = mdy_hm(date_time)) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  pivot_longer(cols = c("1132", "1130", "1124", "1131", "1647"), names_to = "plot", values_to = "soil_moisture") %>% 
  mutate(date = ymd(date), 
         plot = as.numeric(plot), 
         soil_moisture = as.numeric(soil_moisture)) %>% 
  group_by(date, plot) %>% 
  summarise(soil_moisture = mean(soil_moisture)) %>% 
  na.omit()

moisture_logger_2 <- read.csv(here("data", "raw_data", "soil_moisture_data", "Data_loggers", "Hobo_Station_1_(1,2,3,14,15).csv")) %>% 
  rename("434" = "X434") %>% 
  rename("1546" = "X1546") %>% 
  rename("425" = "X425") %>% 
  rename("417" = "X417") %>% 
  rename("423" = "X423") %>% 
  pivot_longer(cols = c("434", "1546", "425", "417", "423"), names_to = "plot", values_to = "soil_moisture") %>% 
  mutate(date_time = mdy_hm(Date.Time..GMT.07.00)) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(date = ymd(date),
         plot = as.numeric(plot)) %>% 
  group_by(date, plot) %>% 
  summarise(soil_moisture = mean(soil_moisture))

moisture_logger_3 <- read.csv(here("data", "raw_data", "soil_moisture_data", "Data_loggers", "Hobo_Station_2_(12,13,4,5)_0.csv")) %>% 
  rename("155" = "X155") %>% 
  rename("166" = "X166") %>% 
  rename("190" = "X190") %>% 
  rename("92" = "X92") %>% 
  rename("203" = "X203") %>% 
  pivot_longer(cols = c("155", "166", "190", "92", "203"), names_to = "plot", values_to = "soil_moisture") %>% 
  mutate(date_time = mdy_hm(Date.Time..GMT.07.00)) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(date = ymd(date),
         plot = as.numeric(plot)) %>% 
  group_by(date, plot) %>% 
  summarise(soil_moisture = mean(soil_moisture))

moisture_logger_4 <- read.csv(here("data", "raw_data", "soil_moisture_data", "Data_loggers", "20841601.csv")) %>% 
  pivot_longer(cols = 3:7, names_to = "plot", values_to = "soil_moisture") %>% 
  mutate(plot = str_remove(plot, "X"),
         plot = as.numeric(plot),
         date_time = mdy_hm(Date.Time..GMT.08.00)) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(date = ymd(date)) %>% 
  group_by(date, plot) %>% 
  summarise(soil_moisture = mean(soil_moisture))

moisture_logger_5 <- read.csv(here("data", "raw_data", "soil_moisture_data", "Data_loggers", "EM12384 28Apr22-1127.csv")) %>% 
  slice(-(1:2)) %>% 
  pivot_longer(cols = 2:6, names_to = "plot", values_to = "soil_moisture") %>% 
  mutate(plot = str_remove(plot, "X"),
         plot = as.numeric(plot), 
         date_time = mdy_hm(EM12384),
         soil_moisture = as.numeric(soil_moisture)) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(date = ymd(date)) %>% 
  group_by(date, plot) %>% 
  summarise(soil_moisture = mean(soil_moisture, na.rm = TRUE))

moisture_logger_6 <- read.csv(here("data", "raw_data", "soil_moisture_data", "Data_loggers", "hobo_1.csv"))%>% 
  pivot_longer(cols = 3:7, names_to = "plot", values_to = "soil_moisture") %>% 
  mutate(plot = str_remove(plot, "X"),
         plot = as.numeric(plot),
         date_time = mdy_hm(Date.Time..GMT.08.00)) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(date = ymd(date)) %>% 
  group_by(date, plot) %>% 
  summarise(soil_moisture = mean(soil_moisture))

moisture_logger_7 <- read.csv(here("data", "raw_data", "soil_moisture_data", "Data_loggers", "hobo_2.csv")) %>% 
  pivot_longer(cols = 3:7, names_to = "plot", values_to = "soil_moisture") %>% 
  mutate(plot = str_remove(plot, "X"),
         plot = as.numeric(plot),
         date_time = mdy_hm(Date.Time..GMT.07.00)) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(date = ymd(date)) %>% 
  group_by(date, plot) %>% 
  summarise(soil_moisture = mean(soil_moisture))

moisture_logger_8 <- read.csv(here("data", "raw_data", "soil_moisture_data", "Data_loggers", "hobo_3.csv")) %>% 
  pivot_longer(cols = 3:7, names_to = "plot", values_to = "soil_moisture") %>% 
  mutate(plot = str_remove(plot, "X"),
         plot = as.numeric(plot),
         date_time = mdy_hm(Date.Time..GMT.07.00)) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(date = ymd(date)) %>% 
  group_by(date, plot) %>% 
  summarise(soil_moisture = mean(soil_moisture))

moisture_logger_9 <- read.csv(here("data", "raw_data", "soil_moisture_data", "Data_loggers", "hobo_4.csv"))%>% 
  pivot_longer(cols = 3:7, names_to = "plot", values_to = "soil_moisture") %>% 
  mutate(plot = str_remove(plot, "X"),
         plot = as.numeric(plot),
         date_time = mdy_hm(Date.Time..GMT.08.00)) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(date = ymd(date)) %>% 
  group_by(date, plot) %>% 
  summarise(soil_moisture = mean(soil_moisture))

moisture_logger_10 <- read.csv(here("data", "raw_data", "soil_moisture_data", "Data_loggers", "hobo_5.csv"))%>% 
  pivot_longer(cols = 3:7, names_to = "plot", values_to = "soil_moisture") %>% 
  mutate(plot = str_remove(plot, "X"),
         plot = as.numeric(plot),
         date_time = mdy_hm(Date.Time..GMT.08.00)) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(date = ymd(date)) %>% 
  group_by(date, plot) %>% 
  summarise(soil_moisture = mean(soil_moisture))

# Continuous moisture over time of 15 plots
moisture_loggers <- rbind(moisture_logger_1,
                          moisture_logger_2, 
                          moisture_logger_3,
                          moisture_logger_4,
                          moisture_logger_5,
                          moisture_logger_6,
                          moisture_logger_7,
                          moisture_logger_8,
                          moisture_logger_9,
                          moisture_logger_10) %>% 
  na.omit() %>% 
  filter(soil_moisture >= 0) %>% 
  mutate(soil_moisture = soil_moisture*100)

write.csv(moisture_loggers, here("data", "clean_data", "soil_moisture_measured.csv"))
```


## Get max daily temperature and then average monthly temperature
## Analyse average monthly temperature similar to soil moisture

```{r}
my_files_1 <- list.files(here("data", "raw_data", "Ibutton_Data", "test"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
my_files_2 <- list.files(here("data", "raw_data", "Ibutton_Data", "2_16_21", "temperature","skip_14"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
my_files_3 <- list.files(here("data", "raw_data", "Ibutton_Data", "2_16_21", "temperature","skip_19"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
my_files_4 <- list.files(here("data", "raw_data", "Ibutton_Data", "4_10_20", "For_R", "Temperature"), 
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
my_files_5 <- list.files(here("data", "raw_data", "Ibutton_Data", "4_23_20", "Raw_Data", "Temperature", "skip_14"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
my_files_6 <- list.files(here("data", "raw_data", "Ibutton_Data", "4_23_20", "Raw_Data", "Temperature", "skip_19"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
my_files_7 <- list.files(here("data", "raw_data", "Ibutton_Data", "10_22_20", "temperature", "skip_14"), 
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
my_files_8 <- list.files(here("data", "raw_data", "Ibutton_Data", "10_22_20", "temperature", "skip_19"), 
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
my_files_9 <- list.files(here("data", "raw_data", "Ibutton_Data", "ibutton", "temperature", "skip_14"), 
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
my_files_10 <- list.files(here("data", "raw_data", "Ibutton_Data", "ibutton", "temperature", "skip_19"), 
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
my_files_11 <- list.files(here("data", "raw_data", "Ibutton_Data", "ibutton_2", "temperature", "skip_14"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
my_files_12 <- list.files(here("data", "raw_data", "Ibutton_Data", "ibutton_2", "temperature", "skip_19"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
ibutton_1 <- read_csv(my_files_1, id = "plot") %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/test/")),
         plot = str_remove(plot, ".csv"),
         plot = as.numeric(plot),
         date_time = mdy_hm(`Date/Time`),
         temperature = as.numeric(Value)) %>% 
  dplyr::select(plot, date_time, temperature) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(date = ymd(date),
         time = hms(time))

ibutton_2 <- read_csv(my_files_2, id = "plot", skip= 14) %>%
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/2_16_21/temperature/skip_14/")),
         plot = str_remove(plot, ".csv"),
         Value = str_remove(Value, "F,"),
         plot = as.numeric(plot),
         date = mdy(`Date/Time`),
         time = hms(Unit),
         temperature = as.numeric(Value)) %>%  
  dplyr::select(plot, date, time, temperature)

ibutton_3 <- read_csv(my_files_3, id = "plot", skip= 19) %>%
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/2_16_21/temperature/skip_19/")),
         plot = str_remove(plot, ".csv"),
         Value = str_remove(Value, "F,"),
         plot = as.numeric(plot),
         date = mdy(`Date/Time`),
         time = hms(Unit),
         temperature = as.numeric(Value)) %>%  
  dplyr::select(plot, date, time, temperature)

ibutton_misc <- read.csv(here("data", "raw_data", "Ibutton_Data", "2_16_21", "temperature", "4.csv"), skip = 19) %>% 
  mutate(plot = 4, 
         date = mdy(Date.Time),
         time = hms(Unit),
         temperature = as.numeric(X)) %>% 
  dplyr::select(plot, date, time, temperature)

ibutton_4 <- read_csv(my_files_4, id = "plot") %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/4_10_20/For_R/Temperature/")),
         plot = str_remove(plot, ".csv"),
         plot = str_remove(plot, "Plot_"),
         plot = str_remove(plot, "T"),
         plot = as.numeric(plot),
         date_time = mdy_hm(`Date/Time`),
         temperature = as.numeric(Value)) %>%  
  dplyr::select(plot, date_time, temperature)%>% 
  separate(date_time, into = c("date", "time"), sep = " ")%>% 
  mutate(date = ymd(date),
         time = hms(time))

ibutton_5 <- read_csv(my_files_5, id = "plot", skip = 14) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/4_23_20/Raw_Data/Temperature/skip_14/")),
         plot = str_remove(plot, ".csv"),
         plot = str_remove(plot, "Plot_"),
         plot = str_remove(plot, "T"),
         plot = as.numeric(plot),
         date_time = mdy_hms(`Date/Time`),
         temperature = as.numeric(Value)) %>%  
  dplyr::select(plot, date_time, temperature)%>% 
  separate(date_time, into = c("date", "time"), sep = " ")%>% 
  mutate(date = ymd(date),
         time = hms(time))

ibutton_6 <- read_csv(my_files_6, id = "plot", skip = 19) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/4_23_20/Raw_Data/Temperature/skip_19/")),
         plot = str_remove(plot, ".csv"),
         plot = str_remove(plot, "Plot_"),
         plot = str_remove(plot, "T"),
         plot = as.numeric(plot),
         date_time = mdy_hms(`Date/Time`),
         temperature = as.numeric(Value),
         temperature = case_when(Unit == "C" ~ temperature*1.8 + 32,
                                 TRUE ~ temperature)) %>%  
  dplyr::select(plot, date_time, temperature)%>% 
  separate(date_time, into = c("date", "time"), sep = " ")%>% 
  mutate(date = ymd(date),
         time = hms(time))

ibutton_7 <- read_csv(my_files_7, id = "plot", skip = 14) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/10_22_20/temperature/skip_14/")),
         plot = str_remove(plot, ".csv"),
         plot = str_remove(plot, "Plot_"),
         plot = str_remove(plot, "T"),
         plot = as.numeric(plot),
         date_time = mdy_hms(`Date/Time`),
         temperature = as.numeric(Value)) %>%  
  dplyr::select(plot, date_time, temperature)%>% 
  separate(date_time, into = c("date", "time"), sep = " ")%>% 
  mutate(date = ymd(date),
         time = hms(time))

ibutton_8 <- read_csv(my_files_8, id = "plot", skip = 19) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/10_22_20/temperature/skip_19/")),
         plot = str_remove(plot, ".csv"),
         plot = str_remove(plot, "Plot_"),
         plot = str_remove(plot, "T"),
         plot = as.numeric(plot),
         date_time = mdy_hms(`Date/Time`),
         temperature = as.numeric(Value)) %>%  
  dplyr::select(plot, date_time, temperature)%>% 
  separate(date_time, into = c("date", "time"), sep = " ")%>% 
  mutate(date = ymd(date),
         time = hms(time))

ibutton_9 <- read_csv(my_files_9, id = "plot", skip = 14) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/ibutton/temperature/skip_14/")),
         plot = str_remove(plot, ".csv"),
         plot = str_remove(plot, "Plot_"),
         plot = str_remove(plot, "T"),
         plot = as.numeric(plot),
         date = mdy(`Date/Time`),
         time = hms(Unit),
         temperature= str_remove(Value, "F,"),
         temperature = as.numeric(temperature)) %>%  
  dplyr::select(plot, date, time, temperature)

ibutton_10 <- read_csv(my_files_10, id = "plot", skip = 19) %>%
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/ibutton/temperature/skip_19/")),
         plot = str_remove(plot, ".csv"),
         plot = str_remove(plot, "Plot_"),
         plot = str_remove(plot, "T"),
         plot = as.numeric(plot),
         date = mdy(`Date/Time`),
         time = hms(Unit),
         temperature= str_remove(Value, "C,"),
         temperature = as.numeric(temperature),
         temperature = temperature*1.8 + 32) %>%  
  dplyr::select(plot, date, time, temperature)

ibutton_11 <- read_csv(my_files_11, id = "plot", skip = 14) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/ibutton_2/temperature/skip_14/")),
         plot = str_remove(plot, ".csv"),
         plot = str_remove(plot, "Plot_"),
         plot = str_remove(plot, "T"),
         plot = as.numeric(plot),
         date_time = mdy_hms(`Date/Time`),
         temperature= str_remove(Value, "F,"),
         temperature = as.numeric(temperature)) %>%  
  dplyr::select(plot, date_time, temperature)%>% 
  separate(date_time, into = c("date", "time"), sep = " ")%>% 
  mutate(date = ymd(date),
         time = hms(time))

ibutton_12 <- read_csv(my_files_12, id = "plot", skip = 19) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/ibutton_2/temperature/skip_19/")),
         plot = str_remove(plot, ".csv"),
         plot = str_remove(plot, "Plot_"),
         plot = str_remove(plot, "T"),
         plot = as.numeric(plot),
         date_time = mdy_hms(`Date/Time`),
         temperature= str_remove(Value, "F,"),
         temperature = as.numeric(temperature)) %>%  
  dplyr::select(plot, date_time, temperature)%>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(date = ymd(date),
         time = hms(time))

ibutton <- rbind(ibutton_1,
                 ibutton_2,
                 ibutton_3, 
                 ibutton_4,
                 ibutton_5,
                 ibutton_6,
                 ibutton_7,
                 ibutton_8,
                 ibutton_9,
                 ibutton_10,
                 ibutton_11,
                 ibutton_12,
                 ibutton_misc)

write.csv(ibutton, here("data", "clean_data", "temperature_measured.csv"))
```

## Humidity 

```{r}
h_files_1 <- list.files(here("data", "raw_data", "Ibutton_Data", "2_16_21","humidity"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
h_files_2 <- list.files(here("data", "raw_data", "Ibutton_Data", "4_10_20", "For_R", "Humidity"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
h_files_3 <- list.files(here("data", "raw_data", "Ibutton_Data", "4_23_20", "Raw_Data", "Humidity"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
h_files_4 <- list.files(here("data", "raw_data", "Ibutton_Data", "10_22_20","humidity"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
h_files_5 <- list.files(here("data", "raw_data", "Ibutton_Data", "ibutton","humidity"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)
h_files_6 <- list.files(here("data", "raw_data", "Ibutton_Data", "ibutton_2","humidity"),
                         pattern = ".csv$", recursive = TRUE, full.names = TRUE)

humidity_1 <- read_csv(h_files_1, id = "plot", skip = 18) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/2_16_21/humidity/")),
         plot = str_remove(plot, "H.csv"),
         plot = as.numeric(plot),
         Value = str_remove(Value, "%RH,"),
         date = mdy(`Date/Time`),
         time = hms(Unit),
         humidity = as.numeric(Value)) %>% 
  dplyr::select(plot, date, time, humidity)

humidity_2 <- read_csv(h_files_2, id = "plot") %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/4_10_20/For_R/Humidity/")),
         plot = str_remove(plot, "Plot_"),
         plot = str_remove(plot, ".csv"),
         plot = str_remove(plot, "H"),
         plot = as.numeric(plot),
         humidity = as.numeric(Value)) %>% 
  separate('Date/Time', into = c("date", "time"), sep = " ") %>% 
  mutate(date = mdy(date),
         time = hm(time)) %>% 
  dplyr::select(plot, date, time, humidity)

humidity_3 <- read_csv(h_files_3, id = "plot", skip = 18) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/4_23_20/Raw_Data/Humidity/")),
         plot = str_remove(plot, "Plot_"),
         plot = str_remove(plot, ".csv"),
         plot = as.numeric(plot),
         humidity = as.numeric(Value),
         `Date/Time` = str_replace(`Date/Time`, " A", "_A"),
         `Date/Time` = str_replace(`Date/Time`, " P", "_P")) %>% 
  separate(`Date/Time`, into = c("date", "time"), sep = " ") %>% 
  mutate(plot = case_when(plot == 11.77 ~ 1177,
                          TRUE ~ plot),
         time = str_replace(time, "_", " "),
         time = parse_time(time, '%I:%M:%S %p'),
         time = hms(time),
         date = mdy(date)) %>% 
  dplyr::select(plot, date, time, humidity)

humidity_4 <- read_csv(h_files_4, id = "plot", skip = 18) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/10_22_20/humidity/")),
         plot = str_remove(plot, "H.csv"),
         plot = as.numeric(plot),
         humidity = as.numeric(Value),
         `Date/Time` = str_replace(`Date/Time`, " A", "_A"),
         `Date/Time` = str_replace(`Date/Time`, " P", "_P")) %>% 
  separate(`Date/Time`, into = c("date", "time"), sep = " ") %>% 
  mutate(date = mdy(date),
         time = str_replace(time, "_", " "),
         time = parse_time(time, '%I:%M:%S %p'),
         time = hms(time)) %>% 
  dplyr::select(plot, date, time, humidity)

humidity_5 <- read_csv(h_files_5, id = "plot", skip = 18) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/ibutton/humidity/")),
         plot = str_remove(plot, "h.csv"),
         plot = as.numeric(plot),
         Value = str_remove(Value, "%RH,"),
         date = mdy(`Date/Time`),
         time = hms(Unit),
         humidity = as.numeric(Value)) %>% 
  dplyr::select(plot, date, time, humidity)

humidity_6 <- read_csv(h_files_6, id = "plot", skip = 18) %>% 
  mutate(plot = str_remove(plot, paste0(here(), "/data/raw_data/Ibutton_Data/ibutton_2/humidity/")),
         plot = str_remove(plot, "H.csv"),
         plot = str_remove(plot, ".csv"),
         plot = as.numeric(plot),
         humidity = as.numeric(Value),
         `Date/Time` = str_replace(`Date/Time`, " A", "_A"),
         `Date/Time` = str_replace(`Date/Time`, " P", "_P")) %>% 
  separate(`Date/Time`, into = c("date", "time"), sep = " ") %>% 
  mutate(date= mdy(date),
         time = str_replace(time, "_", " "),
         time = parse_time(time, '%I:%M:%S %p'),
         time = hms(time)) %>% 
  dplyr::select(plot, date, time, humidity)

humidity <- rbind(humidity_1,
                  humidity_2,
                  humidity_3,
                  humidity_4,
                  humidity_5,
                  humidity_6)

write.csv(humidity, here("data", "clean_data", "humidity_measured.csv"))
```

