---
title: "Untitled"
output: html_document
date: "2024-07-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(survival)
library(gtsummary)
library(patchwork)
```

```{r}
load(here("data", "models", "early_spring_model.rda"))
load(here("data", "models", "summer_model.rda"))
cox_early_spring_model %>% tbl_regression(exp = T)
cox_summer_model %>% tbl_regression(exp = T)
plant_traits <- read.csv(here("data", "clean_data", "cox_plant_traits.csv")) %>% 
  mutate(les_1 = scale(les_1),
         les_2 = scale(les_2),
         wood_density = scale(wood_density),
         wue = scale(wue),
         wue = wue * -1)

environmental <- read.csv(here("data", "clean_data", "predicted_environmental.csv")) %>% 
  select(!X) %>% 
  mutate(date = ymd(date)) %>% 
  group_by(date) %>% 
  mutate(temperature = scale(temperature),
         vpd = scale(vpd)) %>% 
  ungroup()

spring_environmental <- environmental %>% 
  filter(date <= "2020-06-26") %>% 
  group_by(plot_number) %>%
  reframe(soil_moisture = mean(soil_moisture),
          vpd = mean(vpd))

summer_environmental <- environmental %>% 
  filter(date > "2020-06-26" & date <= "2020-09-30") %>% 
  group_by(plot_number) %>%
  reframe(soil_moisture = mean(soil_moisture),
          vpd = mean(vpd))

height <- read.csv(here("data", "clean_data", "height_gopher_kapplin.csv"))%>% 
  dplyr::select(!X) %>% 
   mutate(alive = case_when(dead == 1 ~ 0,
                           dead == 0 ~ 1)) %>% 
  mutate(start_date = ymd(start_date),
         end_date = ymd(end_date),
         height = scale(height))

mean_planting_heights <- height %>% 
  filter(start_date < "2020-06-01") %>% 
  group_by(Plant) %>% 
  reframe(height = mean(height)) %>% 
  rename(species = Plant)

mean_july_heights <- height %>% 
  filter(start_date > "2020-06-01") %>% 
  group_by(Plant) %>% 
  reframe(height = mean(height)) %>% 
  rename(species = Plant)

height_environment_trait<- height %>% 
  left_join(environmental, by = "plot_number", multiple = "all") %>% 
  rename(species = Plant) %>% 
  left_join(plant_traits, by = "species")

cox_early_spring <- height_environment_trait %>% 
  filter(species != "HEWH") %>% 
  filter(date <= "2020-05-30" & end_date <= "2020-06-26") %>% 
  group_by(plot_number) %>%
  reframe(start_time = mean(start_time), 
          end_time = mean(end_time), 
          dead = mean(dead), 
          soil_moisture = mean(soil_moisture), 
          temperature = mean(temperature), 
          vpd = mean(vpd), 
          les_1 = mean(les_1), 
          les_2 = mean(les_2), 
          wood_density = mean(wood_density), 
          wue = mean(wue), 
          height = mean(height))

cox_summer <- height_environment_trait %>% 
  filter(species != "HEWH") %>% 
  filter(end_date > "2020-06-26") %>% 
  filter(date >= start_date & date <= "2020-09-30") %>% 
  group_by(plot_number) %>%
  reframe(start_time = mean(start_time), 
          end_time = mean(end_time), 
          dead = mean(dead), 
          soil_moisture = mean(soil_moisture), 
          temperature = mean(temperature), 
          vpd = mean(vpd), 
          les_1 = mean(les_1), 
          les_2 = mean(les_2), 
          wood_density = mean(wood_density), 
          wue = mean(wue), 
          height = mean(height))
```

```{r}
adfa_test <- summer_environmental %>% 
  select(plot_number, soil_moisture, vpd) %>% 
  mutate(species = "ADFA",
         start_time = 0,
         end_time = 280, 
         dead = 0) %>% 
  left_join(plant_traits, by = "species") %>% 
  left_join(mean_july_heights, by = "species") %>% 
  mutate(prob_alive = predict(cox_summer_model, newdata = ., type = "survival")) %>% 
  filter(prob_alive >= 0.5)

rhov_test <- summer_environmental %>% 
  select(plot_number, soil_moisture, vpd) %>% 
  mutate(species = "RHOV",
         start_time = 0,
         end_time = 280, 
         dead = 0) %>% 
  left_join(plant_traits, by = "species") %>% 
  left_join(mean_july_heights, by = "species") %>% 
  mutate(prob_alive = predict(cox_summer_model, newdata = ., type = "survival")) %>% 
  filter(prob_alive >= 0.5)

enca_test <- summer_environmental %>% 
  select(plot_number, soil_moisture, vpd) %>% 
  mutate(species = "ENCA",
         start_time = 0,
         end_time = 280, 
         dead = 0) %>% 
  left_join(plant_traits, by = "species") %>% 
  left_join(mean_july_heights, by = "species") %>% 
  mutate(prob_alive = predict(cox_summer_model, newdata = ., type = "survival")) %>% 
  filter(prob_alive >= 0.5)

sani_test <- summer_environmental %>% 
  select(plot_number, soil_moisture, vpd) %>% 
  mutate(species = "SANI",
         start_time = 0,
         end_time = 280, 
         dead = 0) %>% 
  left_join(plant_traits, by = "species") %>% 
  left_join(mean_july_heights, by = "species") %>% 
  mutate(prob_alive = predict(cox_summer_model, newdata = ., type = "survival")) %>% 
  filter(prob_alive >= 0.5)

same_test <- summer_environmental %>% 
  select(plot_number, soil_moisture, vpd) %>% 
  mutate(species = "SAME",
         start_time = 0,
         end_time = 280, 
         dead = 0) %>% 
  left_join(plant_traits, by = "species") %>% 
  left_join(mean_july_heights, by = "species") %>% 
  mutate(prob_alive = predict(cox_summer_model, newdata = ., type = "survival")) %>% 
  filter(prob_alive >= 0.5)

top_survivors <- rbind(rhov_test, adfa_test, enca_test, sani_test, same_test) %>% 
  mutate(type = case_when(species %in% c("ENCA", "SANI", "SAME") ~ "Acquisitive/low WUE",
                          species %in% c("ADFA", "RHOV") ~ "Conservative/high WUE"))
top_survivors$species <- factor(top_survivors$species, levels = c("ENCA", "SANI", "SAME", "ADFA", "RHOV"))

top_blank <- ggplot(top_survivors %>% filter(species %in% c("ENCA", "RHOV")), aes(x = soil_moisture, y = vpd))+
  #geom_point(aes(col = species, shape = type),alpha = 0.5)+
  geom_point(data = summer_environmental, aes(x = soil_moisture, y = vpd), alpha = 0.1)+
  theme_classic()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  ylim(-2,2)+
  xlim(-2,2)+
  labs(x = "Soil Moisture",
       y = "Vapor Pressure Deficit")

top_blank

enca_top <- ggplot(top_survivors %>% filter(species == c("ENCA")), aes(x = soil_moisture, y = vpd))+
  geom_point(aes(col = species, shape = type),alpha = 0.5)+
  geom_point(data = summer_environmental, aes(x = soil_moisture, y = vpd), alpha = 0.1)+
  theme_classic()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  ylim(-2,2)+
  xlim(-2,2)+
  labs(x = "Soil Moisture",
       y = "Vapor Pressure Deficit")+ 
  scale_color_manual(values = c("blue"))+
  theme(legend.position = "none")

enca_top

top_survivors$species <- factor(top_survivors$species, levels = c("RHOV", "ENCA"))

both_top <- ggplot(top_survivors %>% filter(species == "RHOV"), aes(x = soil_moisture, y = vpd))+
  geom_point(aes(col = species, shape = type),alpha = 0.5)+
  geom_point(data = summer_environmental, aes(x = soil_moisture, y = vpd), alpha = 0.1)+
  theme_classic()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  ylim(-2,2)+
  xlim(-2,2)+
  labs(x = "Soil Moisture",
       y = "Vapor Pressure Deficit")+ 
  scale_color_manual(values = c("#5D883E"))+
  theme(legend.position = "none")

both_top



ggsave(filename = "top_ony.png",
       plot = top_blank,
       path = here("figures"),
       width = 4, 
       height = 4, 
       units = "in", 
       dpi = 325, 
       scale = 1.5)

ggsave(filename = "both_top.png",
       plot = both_top,
       path = here("figures"),
       width = 4, 
       height = 4, 
       units = "in", 
       dpi = 325, 
       scale = 1.5)

ggsave(filename = "top_enca.png",
       plot = enca_top,
       path = here("figures"),
       width = 4, 
       height = 4, 
       units = "in", 
       dpi = 325, 
       scale = 1.5)
```