---
title: "Untitled"
author: "Shane Dewees"
date: "2022-09-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(broom)
library(partykit)
library(MASS)
library(raster)
library(stars)
library(lubridate)
```

```{r}
growth_topography_raw <- read.csv(here("data", 
                                       "growth_topography_raw.csv")) %>% 
  mutate(Plant = as.factor(Plant)) %>% 
  filter(Plant != "No Plant")
growth_topography_raw$date_dead <- factor(growth_topography_raw$date_dead, 
                                          levels = c("alive", 
                                                     "december2021", 
                                                     "november2020", 
                                                     "july2020", 
                                                     "may2020"))

growth_topography_simple <- growth_topography_raw %>% 
  filter(date == "2020-03-01") %>% 
  dplyr::select(!plot_number & !date & !X & !alive & !stem & !growth) %>% 
  distinct() %>% 
  dplyr::select(date_dead, 
                slope, 
                spring_solar_radiation, 
                winter_solar_radiation, 
                height, 
                diurnal_heat, 
                heat_load, 
                sol_rad_aspect, 
                terrain_ruggedness, 
                sol_rad_aspect)
growth_topography_november <- growth_topography_raw %>% 
  filter(date == "2020-03-01") %>% 
  dplyr::select(!plot_number & !date & !X & !alive & !stem & !growth) %>% 
  distinct() %>% 
  mutate(alive = case_when(date_dead %in% c("november2020", "july2020") ~ 0,
                           date_dead %in% c("december2021", "alive") ~ 1)) %>%
  dplyr::select(alive, 
                slope, 
                spring_solar_radiation, 
                winter_solar_radiation, 
                height, 
                diurnal_heat, 
                heat_load, 
                sol_rad_aspect, 
                terrain_ruggedness, 
                sol_rad_aspect) %>% 
  drop_na()

growth_topography_species_simple <- growth_topography_raw %>% 
  filter(date == "2020-03-01") %>%
  column_to_rownames(var = "plot_number") %>% 
  dplyr::select(!date & !X & !alive & !stem & !growth) %>% 
  distinct() %>% 
 dplyr:: select(date_dead,
                Plant, 
                slope, 
                spring_solar_radiation,
                winter_solar_radiation, 
                height, 
                diurnal_heat, 
                heat_load, 
                sol_rad_aspect, 
                terrain_ruggedness, 
                sol_rad_aspect)
growth_topography_species_november <- growth_topography_raw %>% 
  filter(date == "2020-03-01") %>% 
  dplyr::select(!date & !X & !alive & !stem & !growth) %>% 
  distinct() %>% 
  mutate(alive = case_when(date_dead %in% c("november2020", "july2020") ~ 0,
                           date_dead %in% c("december2021", "alive") ~ 1)) %>%
  dplyr::select(plot_number,
                alive, 
                Plant, 
                slope, 
                spring_solar_radiation, 
                winter_solar_radiation,
                height, 
                diurnal_heat, 
                heat_load, 
                sol_rad_aspect, 
                terrain_ruggedness, 
                sol_rad_aspect) %>% 
  drop_na() %>% 
  column_to_rownames(var = "plot_number")

```

```{r}
lm_data <- growth_topography_raw %>% 
  dplyr::select(!X & !plot_number) %>% 
  filter(date == "2020-03-01") %>% 
  mutate(alive = case_when(date_dead %in% c("december2021", "alive")~1,
                           date_dead %in% c("july2020", "november2020")~0)) %>% 
  dplyr::select(!date & !date_dead & !stem & ! growth) %>% 
  drop_na()

survival_model <- glm(alive~., family = binomial, data = lm_data)
step_model_back <- stepAIC(survival_model, direction = "backward")

best_model <- glm(alive ~ Plant + height + slope + spring_solar_radiation + winter_solar_radiation + 
    diurnal_heat + heat_load + sol_rad_aspect + terrain_ruggedness, family = binomial, data = lm_data)
summary(best_model)
```


```{r}
growth_topography_model <- ctree(as.factor(date_dead) ~.,
                                 data = growth_topography_simple)
plot(growth_topography_model)
growth_november_model <- ctree(as.factor(alive)~., 
                               data = growth_topography_november)
plot(growth_november_model)
```

## Including Species
```{r}
growth_topography_species_model <- ctree(as.factor(date_dead) ~., 
                                         data = growth_topography_species_simple)
plot(growth_topography_species_model)
growth_november_species_model <- ctree(as.factor(alive)~., 
                                       data = growth_topography_species_november)
plot(growth_november_species_model)
```

```{r}
survival_topography_raw <- read.csv(here("data", "survival_topography_raw.csv")) %>% 
  dplyr::select(!X & !date) %>% 
  mutate(alive = case_when(date_dead %in% c("november2020", "july2020", "may2020") ~ 0,
                           date_dead %in% c("alive", "december2021") ~ 1))
survival_topography_raw$alive <- factor(survival_topography_raw$alive, 
                                        levels = c(1, 0))  

survival_topography_stats <- survival_topography_raw %>% 
  dplyr::select(!date_dead) %>% 
  distinct() %>%
  dplyr::select(Plant, 
                alive, 
                slope, 
                spring_solar_radiation,
                winter_solar_radiation, 
                diurnal_heat, 
                heat_load, 
                sol_rad_aspect, 
                terrain_ruggedness) %>% 
  nest(data = c(alive, 
                slope, 
                spring_solar_radiation, 
                winter_solar_radiation, 
                diurnal_heat, 
                heat_load, 
                sol_rad_aspect, 
                terrain_ruggedness)) %>% 
  mutate(slope_ttest = map(data, ~tidy(t.test(slope~alive, .x))),
         spring_ttest = map(data, ~tidy(t.test(spring_solar_radiation~alive, .x))),
         winter_ttest = map(data, ~tidy(t.test(winter_solar_radiation~alive, .x))),
         diurnal_ttest = map(data, ~tidy(t.test(diurnal_heat~alive, .x))),
         heat_ttest = map(data, ~tidy(t.test(heat_load~alive, .x))),
         sol_ttest = map (data, ~tidy(t.test(sol_rad_aspect~alive,.x))),
         terrain_ttest = map(data, ~tidy(t.test(terrain_ruggedness~alive, .x)))) %>% 
  unnest(slope_ttest) %>% 
  rename(slope_difference = estimate,
         slope_low = conf.low,
         slope_high = conf.high) %>% 
  unnest(spring_ttest, names_repair = "unique") %>% 
  rename(spring_difference = estimate, 
         spring_low = conf.low,
         spring_high = conf.high) %>% 
  unnest(winter_ttest, names_repair = "unique") %>% 
  rename(winter_difference = estimate, 
         winter_low = conf.low,
         winter_high = conf.high) %>% 
  unnest(diurnal_ttest, names_repair = "unique") %>% 
  rename(diurnal_heat_difference = estimate, 
         diurnal_heat_low = conf.low,
         diurnal_heat_high = conf.high) %>% 
  unnest(heat_ttest, names_repair = "unique") %>% 
  rename(heat_difference = estimate, 
         heat_low = conf.low,
         heat_high = conf.high) %>% 
  unnest(sol_ttest, names_repair = "unique") %>% 
  rename(sol_difference = estimate, 
         sol_low = conf.low,
         sol_high = conf.high) %>% 
  unnest(terrain_ttest, names_repair = "unique") %>% 
  rename(terrain_difference = estimate, 
         terrain_low = conf.low,
         terrain_high = conf.high) %>% 
  dplyr::select(Plant, 
         slope_difference, 
         slope_high, 
         slope_low,
         spring_difference, 
         spring_low, 
         spring_high, 
         winter_difference, 
         winter_low, 
         winter_high,
         diurnal_heat_difference,
         diurnal_heat_high,
         diurnal_heat_low,
         heat_difference, 
         heat_low,
         heat_high,
         sol_difference,
         sol_low,
         sol_high,
         terrain_difference,
         terrain_low,
         terrain_high)



ggplot(survival_topography_stats, aes(x = spring_difference, y = slope_difference))+
  geom_text(aes(label = Plant))+
  #geom_errorbar(aes(xmin = elevation_low, xmax = elevation_high)) +
  #geom_errorbar(aes(ymin = diurnal_heat_low, ymax = diurnal_heat_high))+
  theme_classic()+
  geom_hline(yintercept = 0, linetype = "dashed")+
  geom_vline(xintercept = 0, linetype = "dashed")
```

## Biomass response metric

```{r}
growth_raster <- raster(here("growth", "growth_raster.tif"))


height_spatial <- rasterToPoints(growth_raster, spatial = TRUE) %>% 
  st_as_sf()
height_spatial <- height_spatial %>% 
  mutate(elevation = raster::extract(elevation, height_spatial),
         aspect = raster::extract(aspect, height_spatial),
         slope = raster::extract(slope, height_spatial),
         spring_solar_radiation = raster::extract(solar_radiation[[2]], height_spatial),
         winter_solar_radiation = raster::extract(solar_radiation[[1]], height_spatial),
         diurnal_heat = raster::extract(diurnal_heat, height_spatial),
         heat_load = raster::extract(heat_load, height_spatial),
         sol_rad_aspect = raster::extract(sol_rad_aspect, height_spatial),
         terrain_ruggedness = raster::extract(terrain_ruggedness, height_spatial))

ggplot(height_spatial, aes(heat_load, growth_raster))+
  geom_point()+
  geom_smooth(method = "lm")

```

```{r}
plant_traits_trimmed_name <- plant_traits_trimmed %>% 
  mutate(Plant = case_when(species == "Adenostoma fasciculatum" ~ "ADFA",
                           species == "Ceanothus oliganthus" ~ "CEOL",
                           species == "Encelia californica" ~ "ENCA",
                           species == "Hesperoyucca whipplei" ~ "HEWH",
                           species == "Heteromeles arbutifolia" ~ "HEAR",
                           species == "Malosma laurina" ~ "MALA",
                           species == "Rhus ovata" ~ "RHOV",
                           species == "Salvia apiana" ~ "SAAP",
                           species == "Salvia mellifera" ~ "SAME",
                           species == "Sambucus nigra" ~ "SANI")) %>% 
  dplyr::select(!species)
growth_topography_traits_simple <- growth_topography_species_simple %>% 
  right_join(plant_traits_trimmed_name, by = "Plant") %>% 
  dplyr::select(!Plant) %>% 
  drop_na()

growth_topography_traits_model <- ctree(as.factor(date_dead) ~., 
                                         data = growth_topography_traits_simple)
plot(growth_topography_traits_model)

growth_topography_traits_november <- growth_topography_species_november %>% 
  right_join(plant_traits_trimmed_name, by = "Plant") %>% 
  dplyr::select(!Plant) %>% 
  drop_na()

growth_topography_traits_november_model <- ctree(as.factor(alive) ~., 
                                         data = growth_topography_traits_november)
plot(growth_topography_traits_november_model)
```






