---
title: "Piru Progress"
author: "Shane Dewees"
date: "12/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(lubridate)
library(sf)
library(raster)
library(tidyverse)
library(stats)
library(jtools)
library(ggparty)
library(partykit)
library(ggfortify)
library(vroom)
library(gmodels)
```

```{r}
planting <- read.csv(here("data", "planting.csv")) %>% 
  rename("plot_number" = "ID")
watering <- read.csv(here("data","watering.csv"))%>% 
  rename("plot_number" = "ID")
measuring <- read.csv(here("data", "measuring.csv"))%>% 
  rename("plot_number" = "ID")
measuring_2 <- read.csv(here("data", "measuring_2.csv"))%>% 
  rename("plot_number" = "ID")
measuring_3 <- read.csv(here("data", "measuring_3.csv"))%>% 
  rename("plot_number" = "ID")

# Table of only plants alive by March 2020
planting_survival <- planting %>% 
  dplyr::select(plot_number, Plant, Height, Date.Planted) %>% 
  mutate(Plant = str_replace_all(string = Plant, pattern = "(White + Pink)", replacement = "")) %>% 
  mutate(Plant = case_when(Plant == "ENCA (Pink)" ~ "ENCA",
                           Plant == "CEOL (Orange)" ~ "CEOL",
                           Plant == "HEWH (White)" ~ "HEWH",
                           Plant == "SAME (Orange + Pink)" ~ "SAME",
                           Plant == "SANI (Orange + Yellow)" ~ "SANI",
                           Plant == "RHOV (White + Pink)" ~ "RHOV",
                           Plant == "SAAP (White + Green)" ~ "SAAP",
                           Plant == "MALA (White + Yellow)" ~ "MALA",
                           Plant == "HEAR" ~ "HEAR",
                           Plant == "ADFA (Orange + Green)" ~ "ADFA",
                           Plant == "RHOV SAAP (White + Pink)" ~ "SAAP",
                           Plant == "ENCA CEOL (Pink)" ~ "CEOL", 
                           Plant == "HEWH (White) RHOV" ~ "RHOV",
                           Plant == "NO PLANT" ~ "No Plant")) %>% 
  filter(Plant != "No Plant", Height != "") %>% 
  mutate(date = my(0320),
         alive = 1) %>% 
  dplyr::select(plot_number,Plant, alive) %>% 
  rename(alive_march2020 = alive)

# Table of plant survival as of May 2020
watering_survival <- watering %>% 
  mutate(Plant = case_when(Plant == "ENCA (Pink)" ~ "ENCA",
                           Plant == "CEOL (Orange)" ~ "CEOL",
                           Plant == "HEWH (White)" ~ "HEWH",
                           Plant == "SAME (Orange + Pink)" ~ "SAME",
                           Plant == "SANI (Orange + Yellow)" ~ "SANI",
                           Plant == "RHOV (White + Pink)" ~ "RHOV",
                           Plant == "SANI (Orange + Yellow) CEOL" ~ "CEOL",
                           Plant == "SAAP (White + Green)" ~ "SAAP",
                           Plant == "MALA (White + Yellow)" ~ "MALA",
                           Plant == "SANI  MALA" ~ "MALA",
                           Plant == "HEAR" ~ "HEAR",
                           Plant == "ADFA (Orange + Green)" ~ "ADFA",
                           Plant == "HEWH (White) ENCA" ~ "ENCA",
                           Plant == "ADFA" ~ "ADFA",
                           Plant == "SANI" ~ "SANI",
                           Plant == "SAME" ~ "SAME",
                           Plant == "SANI " ~ "SANI",
                           Plant == "" ~"No plant")) %>% 
  filter(Plant != "No plant") %>% 
  mutate(alive = case_when(Alive.1 == "y" ~ 1,
                           Alive.1 == "Y" ~ 1,
                           Alive.1 == "n" ~ 0,
                           Alive.1 == "np" ~ 0,
                           Alive.1 == "" ~ 0,
                           Alive.1 == "N" ~ 0,
                           Alive.1 == "NP" ~ 0),
         date = my(0520)) %>% 
  dplyr::select(plot_number,Plant, alive) %>% 
  rename(alive_may2020 = alive)

# Table of plant survival as of July 2020
measuring_survival <- measuring %>% 
  mutate(Plant = case_when(Plant == "ENCA (Pink)" ~ "ENCA",
                           Plant == "CEOL (Orange)" ~ "CEOL",
                           Plant == "HEWH (White)" ~ "HEWH",
                           Plant == "SAME (Orange + Pink)" ~ "SAME",
                           Plant == "SANI (Orange + Yellow)" ~ "SANI", 
                           Plant == "RHOV (White + Pink)" ~ "RHOV",
                           Plant == "SAAP (White + Green)" ~ "SAAP",
                           Plant == "MALA (White + Yellow)" ~ "MALA",
                           Plant == "ADFA (Orange + Green)" ~ "ADFA",
                           Plant == "HEAR" ~ "HEAR",
                           Plant == "ENCA CEOL (Pink)" ~ "CEOL",
                           Plant == "NO PLANT" ~ "No Plant",
                           Plant == "HEWH (White) RHOV" ~ "RHOV",
                           Plant == "HEWH" ~ "HEWH"),
         alive = case_when(Height > 0 ~ 1),
         date = my(0720)) %>% 
  filter(Plant != "No Plant") %>% 
  dplyr::select(plot_number,Plant, alive) %>% 
  rename(alive_july2020 = alive)

# Table of plant survival as of November 2020
measuring_survival_2 <- measuring_2 %>% 
  mutate(Plant = str_replace(Plant, " ", ""),
         alive = case_when(Height > 0 ~ 1,
                           TRUE ~ 0),
         date = my(1120)) %>% 
  filter(Plant != "") %>% 
  dplyr::select(plot_number,Plant, alive) %>%
  rename(alive_november2020 = alive)

# Table of plant survival as of December 2021
measuring_survival_3 <- measuring_3 %>% 
  mutate(alive = case_when(Height > 0 ~ 1),
        date = my(1221)) %>% 
  filter(Plant != "") %>% 
  dplyr::select(plot_number,Plant, alive) %>% 
  rename(alive_december2021 = alive)

# Table of percent each species alive at all dates
survival_raw <- planting_survival %>% 
  left_join(watering_survival, by = "plot_number") %>% 
  left_join(measuring_survival, by = "plot_number") %>% 
  left_join(measuring_survival_2, by = "plot_number") %>% 
  left_join(measuring_survival_3, by = "plot_number") %>% 
  dplyr::select(plot_number, Plant.x, alive_march2020, alive_may2020, alive_july2020, alive_november2020, alive_december2021) %>% 
  pivot_longer(cols = 3:7, names_to = "date", values_to = "alive") %>% 
  mutate(date = case_when(date == "alive_march2020" ~ ym("2020/03"),
                          date == "alive_may2020" ~ ym("2020/05"),
                          date == "alive_july2020" ~ ym("2020/07"),
                          date == "alive_november2020" ~ ym("2020/11"),
                          date == "alive_december2021" ~ ym("2021/12")),
         alive = case_when(is.na(alive) == TRUE ~ 0, 
                           TRUE ~ alive)) %>% 
  rename(Plant = Plant.x)
  
survival <- survival_raw %>% 
  group_by(Plant, date) %>% 
  summarise(alive = sum(alive)) %>% 
  ungroup() %>% 
  mutate(alive_percent = case_when(Plant == "ADFA" ~ alive/148 * 100,
                                   Plant == "CEOL" ~ alive/250 * 100,
                                   Plant == "ENCA" ~ alive/204 * 100,
                                   Plant == "HEAR" ~ alive/121 * 100,
                                   Plant == "HEWH" ~ alive/247 * 100,
                                   Plant == "MALA" ~ alive/89 * 100,
                                   Plant == "RHOV" ~ alive/195 * 100,
                                   Plant == "SAAP" ~ alive/95 * 100,
                                   Plant == "SAME" ~ alive/130 * 100, 
                                   Plant == "SANI" ~ alive/160 * 100),
         Plant = case_when(Plant == "ADFA" ~ "Adenostoma fasciculatum",
                                   Plant == "CEOL" ~ "Ceanothus oliganthus",
                                   Plant == "ENCA" ~ "Encelia californica",
                                   Plant == "HEAR" ~ "Heteromeles arbutifolia",
                                   Plant == "HEWH" ~ "Hesperoyucca whipplei",
                                   Plant == "MALA" ~ "Malosma laurina",
                                   Plant == "RHOV" ~ "Rhus ovata",
                                   Plant == "SAAP" ~ "Salvia apiana",
                                   Plant == "SAME" ~ "Salvia mellifera", 
                                   Plant == "SANI" ~ "Sambucus nigra"))

# Table of percent alive for all species combined
survival_total <- survival %>% 
  group_by(date) %>% 
  summarise(alive = sum(alive))

ggplot(survival, aes(date, alive_percent)) +
  geom_point() +
  geom_line () +
  geom_hline(yintercept = 0,linetype = "dashed")+
  facet_wrap(~Plant, nrow = 5, ncol = 2) +
  labs(y = "Percent Alive") +
  theme_classic()

ggplot(survival, aes(date, alive)) +
  geom_point() +
  geom_line () +
   geom_hline(yintercept = 0,linetype = "dashed")+
  facet_wrap(~Plant, nrow = 5, ncol = 2) +
  theme_classic()

ggplot(survival_total, aes(date, alive)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 0,linetype = "dashed")+
  labs(y = "Number plants alive") +
  theme_classic()
  
```

## Percent Alive by group

```{r}
survival_groups <- survival %>% 
  mutate(community = case_when(Plant %in% c("Encelia californica",
                                              "Hesperoyucca whipplei",
                                              "Salvia apiana",
                                              "Salvia mellifera") ~ "sage scrub",
                               Plant %in% c("Adenostoma fasciculatum",
                                              "Ceanothus oliganthus",
                                              "Heteromeles arbutifolia",
                                              "Malosma laurina",
                                              "Rhus ovata",
                                              "Sambucus nigra") ~ "chaparral")) %>% 
  ungroup()
survival_groups_mean <- survival_groups %>% 
  group_by(date, community) %>% 
  summarise(mean = mean(alive_percent),
            sd = sd(alive_percent)) %>% 
  ungroup()

ggplot(survival_groups_mean, aes(x = date, y = mean, col = community))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd))+
  theme_classic()

survival_groups_stats <- survival_groups %>% 
  dplyr::select(!alive & !Plant) %>% 
  nest(data = c(alive_percent, community)) %>%
  filter(date != "2020-03-01") %>% 
  mutate(t_test = map(data, ~tidy(t.test(alive_percent~community, .x)))) %>% 
  unnest(cols = c(data, t_test)) %>% 
  rename(chaparral_mean = estimate1,
         sage_scrub_mean = estimate2) %>% 
  dplyr::select(date, chaparral_mean, sage_scrub_mean, p.value) %>% 
  distinct() 
```



## Cleaning and initial visualization of growth data

```{r}
# Growth data as of March 2020
planting_growth <- planting %>% 
  mutate(Plant = str_replace_all(string = Plant, pattern = "(White + Pink)", replacement = "")) %>% 
  mutate(Plant = case_when(Plant == "ENCA (Pink)" ~ "ENCA",
                           Plant == "CEOL (Orange)" ~ "CEOL",
                           Plant == "HEWH (White)" ~ "HEWH",
                           Plant == "SAME (Orange + Pink)" ~ "SAME",
                           Plant == "SANI (Orange + Yellow)" ~ "SANI",
                           Plant == "RHOV (White + Pink)" ~ "RHOV",
                           Plant == "SAAP (White + Green)" ~ "SAAP",
                           Plant == "MALA (White + Yellow)" ~ "MALA",
                           Plant == "HEAR" ~ "HEAR",
                           Plant == "ADFA (Orange + Green)" ~ "ADFA",
                           Plant == "RHOV SAAP (White + Pink)" ~ "SAAP",
                           Plant == "ENCA CEOL (Pink)" ~ "CEOL", 
                           Plant == "HEWH (White) RHOV" ~ "RHOV",
                           Plant == "NO PLANT" ~ "No Plant")) %>% 
  filter(Plant != "No Plant", Height != "") %>% 
  mutate(date = my(0320),
         Width.1 = as.numeric(Width.1),
         Width.2 = as.numeric(Width.2)) %>% 
  dplyr::select(plot_number,Plant, Height, Stem.Diameter, Width.1, Width.2) %>%
  mutate(width_march2020 = (Width.1+Width.2)/2) %>% 
  rename(height_march2020 = Height,
         stem_march2020 = Stem.Diameter) %>% 
  dplyr::select(!Width.1 & !Width.2)

# Growth data as of July 2020
measuring_growth <- measuring %>% 
  mutate(Plant = case_when(Plant == "ENCA (Pink)" ~ "ENCA",
                           Plant == "CEOL (Orange)" ~ "CEOL",
                           Plant == "HEWH (White)" ~ "HEWH",
                           Plant == "SAME (Orange + Pink)" ~ "SAME",
                           Plant == "SANI (Orange + Yellow)" ~ "SANI", 
                           Plant == "RHOV (White + Pink)" ~ "RHOV",
                           Plant == "SAAP (White + Green)" ~ "SAAP",
                           Plant == "MALA (White + Yellow)" ~ "MALA",
                           Plant == "ADFA (Orange + Green)" ~ "ADFA",
                           Plant == "HEAR" ~ "HEAR",
                           Plant == "ENCA CEOL (Pink)" ~ "CEOL",
                           Plant == "NO PLANT" ~ "No Plant",
                           Plant == "HEWH (White) RHOV" ~ "RHOV",
                           Plant == "HEWH" ~ "HEWH"),
         date = my(0720),
         Width.1 = as.numeric(Width.1),
         Width.2 = as.numeric(Width.2)) %>% 
  filter(Plant != "No Plant") %>% 
  mutate(width_july2020 = (Width.1+Width.2)/2) %>% 
  dplyr::select(plot_number,Plant, Height, Stem.Diameter, width_july2020) %>%
  rename(height_july2020 = Height,
         stem_july2020 = Stem.Diameter)

# Growth data as of November 2020
measuring_growth_2 <- measuring_2 %>% 
  mutate(Plant = str_replace(Plant, " ", ""),
         date = my(1120),
         Width.1 = as.numeric(Width.1),
         Width.2 = as.numeric(Width.2)) %>% 
  filter(Plant != "") %>% 
  mutate(width_november2020 = (Width.1+Width.2)/2) %>% 
  dplyr::select(plot_number,Plant, Height, Stem.Diameter, width_november2020) %>% 
  rename(height_november2020 = Height,
         stem_november2020 = Stem.Diameter)

# Growth data as of December 2021
measuring_growth_3 <- measuring_3 %>% 
  mutate(date = my(1221),
         Width.1 = as.numeric(Width.1),
         Width.2 = as.numeric(Width.2),
         width_december2021 = (Width.1 + Width.2)/2) %>% 
  filter(Plant != "") %>% 
  dplyr::select(plot_number,Plant, Height, Stem.Diameter, width_december2021) %>% 
  rename(height_december2021 = Height,
         stem_december2021 = Stem.Diameter)

# Growth data grouped by species for all dates
growth_raw <- planting_growth %>% 
  left_join(measuring_growth, by = "plot_number") %>% 
  left_join(measuring_growth_2, by = "plot_number") %>% 
  left_join(measuring_growth_3, by = "plot_number") %>% 
  dplyr::select(plot_number, Plant.x, height_march2020, height_july2020, height_november2020, height_december2021,
         stem_march2020, stem_july2020, stem_november2020, stem_december2021) %>% 
  mutate(height_march2020 = as.numeric(height_march2020),
         stem_march2020 = as.numeric(stem_march2020),
         stem_july2020 = as.numeric(stem_july2020),
         stem_november2020 = as.numeric(stem_november2020),
         stem_december2021 = as.numeric(stem_december2021),
         growth_july2020 = height_july2020 - height_march2020,
         growth_november2020 = height_november2020 - height_july2020,
         growth_december2021 = height_december2021 - height_november2020) %>% 
  pivot_longer(3:13, names_to = "names", values_to = "values") %>% 
  separate(names, into = c("variables", "date")) %>% 
  pivot_wider(names_from = "variables", values_from = "values") %>% 
  mutate(date = case_when(date == "march2020" ~ ym("2020/03"),
                          date == "july2020" ~ ym("2020/07"),
                          date == "november2020" ~ ym("2020/11"),
                          date == "december2021" ~ ym("2021/12"))) %>% 
  rename(Plant = Plant.x) %>% 
  left_join(survival_raw, by = c("plot_number", "Plant", "date"))

growth <- growth_raw %>%
  group_by(plot_number) %>% 
  mutate(alive_sum = sum(alive),
         date_dead = case_when(alive_sum == 1 ~ "july2020",
                               alive_sum == 2 ~ "november2020", 
                               alive_sum == 3 ~ "december2021",
                               alive_sum == 4 ~ "alive")) %>% 
  ungroup()

july_dead_stats <- growth %>% 
  filter(date == "2020/03/01") %>% 
  mutate(alive = case_when(date_dead == "july2020" ~ 0,
                           TRUE ~ alive)) %>% 
  dplyr::select(Plant, height, alive, stem) %>% 
  nest(data = c(height, alive, stem)) %>% 
  mutate(t_test_height = map(data, ~tidy(t.test(height~alive, .x))),
         t_test_stem = map(data, ~tidy(t.test(stem~alive, .x)))) %>% 
  unnest(cols = t_test_height) %>% 
  dplyr::select(Plant, estimate1, estimate2, p.value, t_test_stem) %>% 
  distinct() %>% 
  rename(dead_height = estimate1,
         alive_height = estimate2,
         pvalue_height = p.value) %>% 
  unnest(cols = t_test_stem) %>% 
  dplyr::select(Plant, dead_height, alive_height, pvalue_height, estimate1, estimate2, p.value) %>% 
  rename(dead_stem = estimate1,
         alive_stem = estimate2,
         pvalue_stem = p.value) %>% 
  distinct()

november_dead_stats <- growth %>% 
  filter(date == "2020/07/01" & date_dead != "july2020") %>% 
  mutate(alive = case_when(date_dead == "november2020" ~ 0,
                           TRUE ~ alive)) %>%
  dplyr::select(Plant, height, alive, growth) %>% 
  drop_na() %>%
  nest(data = c(height, alive, growth)) %>% 
  mutate(t_test_height = map(data, ~tidy(t.test(height~alive, .x))),
         t_test_growth = map(data, ~tidy(t.test(growth~alive, .x)))) %>% 
  unnest(cols = t_test_height) %>% 
  dplyr::select(Plant, estimate1, estimate2, p.value, t_test_growth) %>% 
  distinct() %>% 
  rename(dead_height = estimate1,
         alive_height = estimate2,
         pvalue_height = p.value) %>% 
  unnest(cols = t_test_growth) %>% 
  dplyr::select(Plant, dead_height, alive_height, pvalue_height, estimate1, estimate2, p.value) %>% 
  distinct() %>% 
  rename(dead_growth = estimate1,
         alive_growth = estimate2,
         pvalue_growth = p.value)

november_stem_stats <- growth %>% 
  filter(date == "2020/07/01" & date_dead != "july2020") %>% 
  filter(Plant != "HEWH") %>% 
  mutate(alive = case_when(date_dead == "november2020" ~ 0,
                           TRUE ~ alive)) %>%
  dplyr::select(Plant, stem, alive) %>% 
  drop_na() %>%
  nest(data = c(stem, alive)) %>% 
  mutate(t_test_stem = map(data, ~tidy(t.test(stem~alive, .x)))) %>% 
  unnest(cols = t_test_stem) %>% 
  dplyr::select(Plant, estimate1, estimate2, p.value) %>% 
  distinct() %>% 
  rename(dead_stem = estimate1,
         alive_stem = estimate2,
         pvalue_stem = p.value)

december_dead_stats <- growth %>% 
  filter(date == "2020/11/01" & date_dead %in% c("december2021", "alive")) %>% 
  mutate(alive = case_when(date_dead == "december2021" ~ 0,
                           TRUE ~ alive)) %>% 
  filter(Plant %in% c("ENCA", "SAME","RHOV","HEWH", "SAAP", "ADFA", "MALA", "SANI")) %>% 
  dplyr::select(Plant, height, alive, growth) %>% 
  drop_na() %>%
  nest(data = c(height, alive, growth)) %>% 
  mutate(t_test_height = map(data, ~tidy(t.test(height~alive, .x))),
         t_test_growth = map(data, ~tidy(t.test(growth~alive, .x)))) %>% 
  unnest(cols = t_test_height) %>% 
  dplyr::select(Plant, estimate1, estimate2, p.value, t_test_growth) %>% 
  distinct() %>% 
  rename(dead_height = estimate1,
         alive_height = estimate2,
         pvalue_height = p.value) %>% 
  unnest(cols = t_test_growth) %>% 
  dplyr::select(Plant, dead_height, alive_height, pvalue_height, estimate1, estimate2, p.value) %>% 
  distinct() %>% 
  rename(dead_growth = estimate1,
         alive_growth = estimate2,
         pvalue_growth = p.value)

december_stem_stats <- growth %>% 
  filter(date == "2020/11/01" & date_dead %in% c("december2021", "alive")) %>% 
  filter(Plant != "HEWH") %>% 
  mutate(alive = case_when(date_dead == "december2021" ~ 0,
                           TRUE ~ alive)) %>% 
  dplyr::select(Plant, stem, alive) %>% 
  drop_na() %>%
  filter(Plant %in% c("ENCA", "SAME","RHOV", "SAAP", "ADFA", "MALA", "SANI")) %>% 
  nest(data = c(stem, alive)) %>% 
  mutate(t_test_stem = map(data, ~tidy(t.test(stem~alive, .x)))) %>% 
  unnest(cols = t_test_stem) %>% 
  dplyr::select(Plant, estimate1, estimate2, p.value) %>% 
  distinct() %>% 
  rename(dead_stem = estimate1,
         alive_stem = estimate2,
         pvalue_stem = p.value)
```

## Making growth_spatial

```{r}
plots <- st_read(here("data", "plot_gps_points.shp")) %>% 
  rename("plot_number" = "plt_nmb")

growth_spatial <- planting_growth %>% 
  left_join(measuring_growth,
            by = "plot_number") %>% 
  left_join(measuring_growth_2, 
            by = "plot_number") %>% 
  left_join(measuring_growth_3, 
            by = "plot_number") %>% 
  dplyr::select(plot_number, 
         Plant.x, 
         height_march2020, 
         height_november2020,
         stem_march2020, 
         stem_november2020,
         width_march2020,
         width_november2020) %>% 
  drop_na() %>% 
  mutate(height_march2020 = as.numeric(height_march2020),
         height_november2020 = as.numeric(height_november2020),
         stem_march2020 = as.numeric(stem_march2020),
         stem_november2020 = as.numeric(stem_november2020),
         growth_height = height_november2020 - height_march2020,
         growth_stem = stem_november2020 - stem_march2020,
         growth_width = width_november2020 - width_march2020,
         height_zscore = (growth_height - mean(growth_height))/sd(growth_height),
         stem_zscore = (growth_stem - mean(growth_stem, na.rm = TRUE))/sd(growth_stem, na.rm = TRUE),
         stem_zscore = replace_na(stem_zscore, 0),
         width_zscore = (growth_width - mean(growth_width))/sd(growth_width),
         growth_zscore = height_zscore + stem_zscore + width_zscore) %>% 
  dplyr::select(plot_number, growth_zscore) %>% 
  full_join(plots, by = "plot_number") %>% 
  drop_na()

```


## Looking at survival without gopher kill 
  - unintuitably labelled gopher

```{r}
# Survival in May 2020
watering_gopher <- watering %>% 
  dplyr::select(plot_number, Watering.2.Date, Alive.1, Notes.1) %>% 
  rename("watering_date" = "Watering.2.Date",
         "watering_alive" = "Alive.1", 
         "watering_notes" = "Notes.1") 

# Growth & survival by July 2020 (gophers incl.)
measuring_gopher <- measuring %>% 
  dplyr::select(!Plant) %>% 
  rename("measuring_height" = "Height",
         "measuring_width_1" = "Width.1",
         "measuring_width_2" = "Width.2",
         "measuring_stem_diameter" = "Stem.Diameter",
         "measuring_date" = "Date.Measured",
         "measuring_notes" = "Notes")

# Growth & survival by November 2020 (gophers incl.)
measuring_gopher_2 <- measuring_2 %>% 
  dplyr::select(!Plant) %>%
  rename("measuring_2_height" = "Height",
         "measuring_2_width_1" = "Width.1",
         "measuring_2_width_2" = "Width.2",
         "measuring_2_stem_diameter" = "Stem.Diameter",
         "measuring_2_date" = "Date.Measured",
         "measuring_2_notes" = "Notes")

# Growth & survival by December 2021 (gophers incl.)
measuring_gopher_3 <- measuring_3 %>% 
  dplyr::select(!Plant) %>%
  rename("measuring_3_height" = "Height",
         "measuring_3_width_1" = "Width.1",
         "measuring_3_width_2" = "Width.2",
         "measuring_3_stem_diameter" = "Stem.Diameter",
         "measuring_3_date" = "Date.Measured",
         "measuring_3_notes" = "Notes")

# Joined table of growth/survival with all dates, gophers excluded
survival_gopher <- left_join(planting, watering_gopher, by = "plot_number") %>% 
  left_join(measuring_gopher, by = "plot_number") %>% 
  left_join(measuring_gopher_2, by = "plot_number") %>% 
  left_join(measuring_gopher_3, by = "plot_number") %>%  
  filter(watering_notes != "gopher", 
         watering_notes != "gopher activity", 
         watering_notes != "GOPHER", 
         watering_notes != "GOPHER ACTIVITY", 
         watering_notes != "5/15 np") %>% 
  filter(measuring_notes != "np", 
         measuring_notes != "np, g", 
         measuring_notes != "np, buried", 
         measuring_notes != "g.a.",
         measuring_notes != "dead, g.a.", 
         measuring_notes != "np, g.a.", 
         measuring_notes != "dead, g", 
         measuring_notes != "np, g (no coin catch#2)", 
         measuring_notes != "np,g",
         measuring_notes!= "herbivorized, g.a.") %>% 
  filter(measuring_2_notes != "NP", 
         measuring_2_notes != "MISSING", 
         measuring_2_notes != "NP ", 
         measuring_2_notes != "GOPHER", 
         measuring_2_notes != "NP? NO TAG", 
         measuring_2_notes != "MISSNG") %>%
  filter(measuring_3_notes != "NP")%>% 
  mutate(Plant = str_replace_all(string = Plant, pattern = "(White + Pink)", replacement = "")) %>% 
  mutate(Plant = case_when(Plant == "ENCA (Pink)" ~ "ENCA",
                           Plant == "CEOL (Orange)" ~ "CEOL",
                           Plant == "HEWH (White)" ~ "HEWH",
                           Plant == "SAME (Orange + Pink)" ~ "SAME",
                           Plant == "SANI (Orange + Yellow)" ~ "SANI",
                           Plant == "RHOV (White + Pink)" ~ "RHOV",
                           Plant == "SAAP (White + Green)" ~ "SAAP",
                           Plant == "MALA (White + Yellow)" ~ "MALA",
                           Plant == "HEAR" ~ "HEAR",
                           Plant == "ADFA (Orange + Green)" ~ "ADFA",
                           Plant == "RHOV SAAP (White + Pink)" ~ "SAAP",
                           Plant == "ENCA CEOL (Pink)" ~ "CEOL", 
                           Plant == "HEWH (White) RHOV" ~ "RHOV",
                           Plant == "NO PLANT" ~ "No Plant"))

# Survival data as of March 2020, excl. gopher
planting_survival_gopher <- survival_gopher %>% 
  dplyr::select(plot_number,Plant, Height, Date.Planted) %>% 
  filter(Plant != "No Plant", Height != "") %>% 
  mutate(alive_march2020 = 1) %>% 
  dplyr::select(plot_number,Plant, alive_march2020)

# Surival as of May 2020, excl. gopher
watering_survival_gopher <- survival_gopher %>%
  dplyr::select(plot_number,Plant, watering_alive, watering_date) %>%
  filter(Plant != "No plant") %>% 
  mutate(alive_may2020 = case_when(watering_alive == "y" ~ 1,
                           watering_alive == "Y" ~ 1,
                           watering_alive == "n" ~ 0,
                           watering_alive == "np" ~ 0,
                           watering_alive == "" ~ 0,
                           watering_alive == "N" ~ 0,
                           watering_alive == "NP" ~ 0)) %>% 
  dplyr::select(plot_number,Plant, alive_may2020)

# Survival as of July 2020, excl. gopher
measuring_survival_gopher <- survival_gopher %>% 
  dplyr::select(plot_number,Plant, measuring_height, measuring_date) %>% 
  mutate(alive_july2020 = case_when(measuring_height > 0 ~ 1, 
                           TRUE ~0)) %>% 
  filter(Plant != "No Plant") %>% 
  dplyr::select(plot_number,Plant, alive_july2020)

# Survival as of November 2020
measuring_survival_gopher_2 <- survival_gopher %>% 
  dplyr::select(plot_number,Plant, measuring_2_height, measuring_2_date) %>% 
  mutate(alive_november2020 = case_when(measuring_2_height > 0 ~ 1,
                           TRUE ~ 0)) %>% 
  filter(Plant != "") %>% 
  dplyr::select(plot_number,Plant, alive_november2020)

# Survival as of December 2021, excl. gopher
measuring_survival_gopher_3 <- survival_gopher %>% 
  dplyr::select(plot_number,Plant, measuring_3_height, measuring_3_date) %>% 
  mutate(alive_december2021 = case_when(measuring_3_height > 0 ~ 1, 
                           TRUE ~ 0)) %>% 
  filter(Plant != "") %>% 
  dplyr::select(plot_number,Plant, alive_december2021)

# Survival grouped by species with all dates, excl. gopher, with pretty field names
gopher_raw <- planting_survival_gopher %>% 
  left_join(watering_survival_gopher, by = "plot_number") %>% 
  left_join(measuring_survival_gopher, by = "plot_number") %>% 
  left_join(measuring_survival_gopher_2, by = "plot_number") %>% 
  left_join(measuring_survival_gopher_3, by = "plot_number")

survival_gopher_raw <- gopher_raw %>% 
  dplyr::select(plot_number, Plant.x, alive_march2020, alive_may2020, alive_july2020, alive_november2020, alive_december2021) %>% 
  rename(Plant = Plant.x) %>% 
  pivot_longer(cols = 3:7, names_to = "date", values_to = "alive") %>% 
  mutate(date = case_when(date == "alive_march2020" ~ ym(2003),
                          date == "alive_may2020" ~ ym(2005),
                          date == "alive_july2020" ~ ym(2007),
                          date == "alive_november2020" ~ ym(2011),
                          date == "alive_december2021" ~ ym(2112))) 
survival_gopher_clean <- survival_gopher_raw %>% 
  dplyr::select(!plot_number) %>% 
  group_by(Plant, date) %>% 
  mutate(alive = sum(alive, na.rm = TRUE)) %>% 
  ungroup() %>% 
  filter(Plant != "No Plant") %>% 
  mutate(alive_percent = case_when(Plant == "ADFA" ~ alive/118 * 100,
                                   Plant == "CEOL" ~ alive/97 * 100,
                                   Plant == "ENCA" ~ alive/83 * 100,
                                   Plant == "HEAR" ~ alive/61 * 100,
                                   Plant == "HEWH" ~ alive/80 * 100,
                                   Plant == "MALA" ~ alive/43 * 100,
                                   Plant == "RHOV" ~ alive/75 * 100,
                                   Plant == "SAAP" ~ alive/45 * 100,
                                   Plant == "SAME" ~ alive/48 * 100, 
                                   Plant == "SANI" ~ alive/62 * 100),
         community = case_when(Plant %in% c("ADFA", "CEOL", "HEAR", "MALA", "RHOV", "SANI")~ "chaparral",
                               Plant %in% c("ENCA", "HEWH", "SAAP", "SAME") ~ "sage scrub"),
         Plant = case_when(Plant == "ADFA" ~ "Adenostoma fasciculatum",
                                   Plant == "CEOL" ~ "Ceanothus oliganthus",
                                   Plant == "ENCA" ~ "Encelia californica",
                                   Plant == "HEAR" ~ "Heteromeles arbutifolia",
                                   Plant == "HEWH" ~ "Hesperoyucca whipplei",
                                   Plant == "MALA" ~ "Malosma laurina",
                                   Plant == "RHOV" ~ "Rhus ovata",
                                   Plant == "SAAP" ~ "Salvia apiana",
                                   Plant == "SAME" ~ "Salvia mellifera", 
                                   Plant == "SANI" ~ "Sambucus nigra")) %>% 
  distinct()
survival_gopher_clean$Plant <- factor(survival_gopher_clean$Plant, 
                                      levels = c("Adenostoma fasciculatum", 
                                                 "Ceanothus oliganthus",
                                                 "Heteromeles arbutifolia",
                                                 "Malosma laurina",
                                                 "Rhus ovata",
                                                 "Sambucus nigra",
                                                 "Encelia californica",
                                                 "Hesperoyucca whipplei",
                                                 "Salvia apiana",
                                                 "Salvia mellifera"))
# Survival of all species combined with all dates, excl. gopher, with pretty field names
survival_gopher_total <- survival_gopher_clean %>% 
  group_by(date) %>% 
  summarise(alive = sum(alive))

ggplot(survival_gopher_clean, aes(date, alive_percent, col = community)) +
  geom_point() +
  geom_line () +
  facet_wrap(vars(Plant), nrow = 5, ncol = 2) +
  labs(y = "Percent Alive") +
  theme_classic()

ggplot(survival, aes(date, alive)) +
  geom_point() +
  geom_line () +
  facet_wrap(~Plant, nrow = 5, ncol = 2) +
  theme_classic()

ggplot(survival_total, aes(date, alive)) +
  geom_point() +
  geom_line() +
  labs(y = "Number plants alive") +
  theme_classic()
```

## Gopher survival by community 

```{r}
gopher_survival_groups <- survival_gopher_clean %>% 
  mutate(community = case_when(Plant %in% c("Encelia californica",
                                            "Hesperoyucca whipplei",
                                            "Salvia apiana",
                                            "Salvia mellifera",
                                            "Sambucus nigra") ~ "sage scrub",
                               Plant %in% c("Adenostoma fasciculatum",
                                              "Ceanothus oliganthus",
                                              "Heteromeles arbutifolia",
                                              "Malosma laurina",
                                              "Rhus ovata") ~ "chaparral")) %>% 
  ungroup()
gopher_survival_groups_mean <- gopher_survival_groups %>% 
  group_by(date, community) %>% 
  summarise(mean = mean(alive_percent),
            upper = ci(alive_percent, na.rm = TRUE)[3],
            lower = ci(alive_percent, na.rm = TRUE)[2]) %>% 
  ungroup()

gopher_survival_groups_stats <- gopher_survival_groups %>% 
  dplyr::select(!alive & !Plant) %>% 
  nest(data = c(alive_percent, community)) %>%
  filter(date != "2020-03-01") %>% 
  mutate(t_test = map(data, ~tidy(t.test(alive_percent~community, .x)))) %>% 
  unnest(cols = c(data, t_test)) %>% 
  rename(chaparral_mean = estimate1,
         sage_scrub_mean = estimate2) %>% 
  dplyr::select(date, chaparral_mean, sage_scrub_mean, p.value) %>% 
  distinct() %>% 
  mutate(p.value = round(p.value, digits = 3))

gopher_survival_groups_mean <- gopher_survival_groups_mean %>% 
  left_join(gopher_survival_groups_stats, by = "date")
  

ggplot()+
  geom_point(data = gopher_survival_groups_mean, 
             aes(x = date, y = mean, col = community))+
  geom_line(data = gopher_survival_groups_mean,
            aes(x = date, y = mean, col = community))+
  geom_text(data = gopher_survival_groups_mean %>% filter(date != "2020-03-01" & community == "chaparral"),
            aes(x = date, y = 105, label = paste("p =", p.value)),
            size = 2.5)+
  geom_errorbar(data = gopher_survival_groups_mean, 
                aes(x = date, ymin = lower, ymax = upper, col = community))+
  theme_classic()+
  labs(y = "percent survival")
```

## Gopher growth

```{r}
gopher_growth <- survival_gopher %>% 
  dplyr::select(plot_number, 
         Plant, 
         Height, 
         Stem.Diameter, 
         measuring_height, 
         measuring_stem_diameter, 
         measuring_2_height, 
         measuring_2_stem_diameter, 
         measuring_3_height, 
         measuring_3_stem_diameter) %>% 
  rename(march_height = Height, 
         march_stem = Stem.Diameter,
         july_height = measuring_height,
         july_stem = measuring_stem_diameter,
         november_height = measuring_2_height, 
         november_stem = measuring_2_stem_diameter,
         december_height = measuring_3_height,
         december_stem = measuring_3_stem_diameter) %>% 
  mutate(march_height = as.numeric(march_height),
         march_stem = as.numeric(march_stem),
         july_stem = as.numeric(july_stem),
         november_stem = as.numeric(november_stem),
         july_growth = july_height - march_height,
         november_growth = november_height - july_height,
         december_growth = december_height - november_height) %>% 
  pivot_longer(cols = 3:13, names_to = "names", values_to = "values") %>% 
  separate(names, into = c("date", "measurement")) %>% 
  pivot_wider(names_from = "measurement", values_from = "values") %>% 
  mutate(date = case_when(date == "march" ~ ym(2003),
                          date == "july" ~ ym(2007),
                          date == "november" ~ ym(2011),
                          date == "december" ~ ym(2112)),
         alive = case_when(is.na(height) == FALSE ~ 1,
                           is.na(height) == TRUE ~ 0)) %>%
  group_by(plot_number) %>% 
  mutate(date_dead = sum(alive)) %>% 
  ungroup() %>% 
  filter(date_dead != 0) %>% 
  mutate(date_dead = case_when(date_dead == 1 ~ "july2020",
                               date_dead == 2 ~ "november2020",
                               date_dead == 3 ~ "december2021",
                               date_dead == 4 ~ "alive"))

gopher_height_july_mean <- gopher_growth %>% 
  filter(date == "2020-03-01") %>% 
  filter(Plant != "No Plant") %>% 
  mutate(alive = case_when(date_dead == "july2020" ~ 0,
                           TRUE ~ alive)) %>% 
  dplyr::select(Plant, height, alive) %>% 
  group_by(Plant, alive) %>% 
  summarise(mean = ci(height, na.rm = TRUE)[1],
            lower = ci(height, na.rm = TRUE)[2],
            upper = ci(height, na.rm = TRUE)[3])

gopher_height_july_stats <- gopher_growth %>%
  filter(date == "2020-03-01") %>% 
  filter(Plant != "No Plant") %>% 
  mutate(alive = case_when(date_dead == "july2020" ~ 0,
                           TRUE ~ alive)) %>% 
  dplyr::select(Plant, height, alive) %>% 
  nest(data = c(height, alive)) %>% 
  mutate(height_ttest = map(data, ~tidy(t.test(height~alive, .x)))) %>% 
  unnest(height_ttest) %>% 
  dplyr::select(Plant, p.value) %>% 
  mutate(p.value = round(p.value, digits = 3)) %>% 
  full_join(gopher_height_july_mean, by = "Plant") %>% 
  mutate(community = case_when(Plant %in% c("ADFA", "CEOL", "HEAR", "MALA", "RHOV","SANI") ~ "chaparral",
                               Plant %in% c("ENCA", "HEWH", "SAAP", "SAME") ~ "sage scrub"),
         alive = case_when(alive == 0 ~ "dead",
                           alive == 1 ~ "alive"))
gopher_height_july_stats$Plant <- factor(gopher_height_july_stats$Plant, 
                                         levels = c("ADFA", "CEOL", "HEAR", "MALA", "RHOV", "SANI",
                                                    "ENCA", "HEWH", "SAAP","SAME"))

gopher_height_november_mean <- gopher_growth %>% 
  filter(date == "2020-07-01" & date_dead != "july2020") %>% 
  filter(Plant != "No Plant") %>% 
  mutate(alive = case_when(date_dead == "november2020" ~ 0,
                           TRUE ~ alive)) %>% 
  dplyr::select(Plant, height, alive) %>% 
  group_by(Plant, alive) %>% 
  summarise(mean = ci(height, na.rm = TRUE)[1],
            lower = ci(height, na.rm = TRUE)[2],
            upper = ci(height, na.rm = TRUE)[3])

gopher_height_november_stats <- gopher_growth %>% 
  filter(date == "2020-07-01" & date_dead != "july2020") %>% 
  filter(Plant != "No Plant") %>% 
  mutate(alive = case_when(date_dead == "november2020" ~ 0,
                           TRUE ~ alive)) %>% 
  dplyr::select(Plant, height, alive) %>% 
  nest(data = c(height, alive)) %>% 
  mutate(height_ttest = map(data, ~tidy(t.test(height~alive, .x)))) %>% 
  unnest(height_ttest) %>% 
  dplyr::select(Plant, p.value) %>%
  mutate(p.value = round(p.value, digits = 3))%>% 
  full_join(gopher_height_november_mean, by = "Plant") %>% 
  mutate(community = case_when(Plant %in% c("ADFA", "CEOL", "HEAR", "MALA", "RHOV","SANI") ~ "chaparral",
                               Plant %in% c("ENCA", "HEWH", "SAAP", "SAME") ~ "sage scrub"),
         alive = case_when(alive == 0 ~ "dead",
                           alive == 1 ~ "alive"))
gopher_height_november_stats$Plant <- factor(gopher_height_november_stats$Plant, 
                                         levels = c("ADFA", "CEOL", "HEAR", "MALA", "RHOV", "SANI",
                                                    "ENCA", "HEWH", "SAAP","SAME"))

gopher_height_december_mean <- gopher_growth %>% 
  filter(date == "2020-11-01" & date_dead %in% c("december2021", "alive")) %>% 
  filter(Plant != "No Plant") %>% 
  filter(Plant != "HEAR") %>% 
  filter(Plant != "CEOL") %>% 
  mutate(alive = case_when(date_dead == "december2021" ~ 0,
                           TRUE ~ alive)) %>% 
  dplyr::select(Plant, height, alive) %>% 
  group_by(Plant, alive) %>% 
  summarise(mean = ci(height, na.rm = TRUE)[1],
            lower = ci(height, na.rm = TRUE)[2],
            upper = ci(height, na.rm = TRUE)[3])

gopher_height_december_stats <- gopher_growth %>% 
  filter(date == "2020-11-01" & date_dead %in% c("december2021", "alive")) %>% 
  filter(Plant != "No Plant") %>% 
  filter(Plant != "HEAR") %>% 
  filter(Plant != "CEOL") %>% 
  mutate(alive = case_when(date_dead == "december2021" ~ 0,
                           TRUE ~ alive)) %>% 
  dplyr::select(Plant, height, alive) %>% 
  nest(data = c(height, alive)) %>% 
  mutate(height_ttest = map(data, ~tidy(t.test(height~alive, .x)))) %>% 
  unnest(height_ttest) %>% 
  dplyr::select(Plant,p.value) %>% 
  mutate(p.value = round(p.value, digits = 3)) %>% 
  full_join(gopher_height_december_mean, by = "Plant") %>% 
  mutate(community = case_when(Plant %in% c("ADFA", "MALA", "RHOV","SANI") ~ "chaparral",
                               Plant %in% c("ENCA", "HEWH", "SAAP", "SAME") ~ "sage scrub"),
         alive = case_when(alive == 0 ~ "dead",
                           alive == 1 ~ "alive"))
gopher_height_december_stats$Plant <- factor(gopher_height_december_stats$Plant, 
                                         levels = c("ADFA", "MALA", "RHOV", "SANI",
                                                    "ENCA", "HEWH", "SAAP","SAME"))

ggplot(gopher_height_july_stats)+
  geom_point(aes(x = Plant, y = mean, shape = alive, col = community))+
  geom_errorbar(aes(x = Plant, ymin = lower, ymax = upper, col = community)) +
  geom_text(aes(x = Plant, y = 60, label = paste("p =", p.value)), size = 3)+
  theme_classic()+
  labs (x = "Species",
        y = "Height (cm)")
ggplot(gopher_height_november_stats)+
  geom_point(aes(x = Plant, y = mean, shape = alive, col = community))+
  geom_errorbar(aes(x = Plant, ymin = lower, ymax = upper, col = community)) +
  geom_text(aes(x = Plant, y = 55, label = paste("p =", p.value)), size = 3) +
  theme_classic() +
  labs(x = "Species",
       y = "Height (cm)")
ggplot(gopher_height_december_stats)+
  geom_point(aes(x = Plant, y = mean, shape = alive, col = community))+
  geom_errorbar(aes(x = Plant, ymin = lower, ymax = upper, col = community)) +
  geom_text(aes(x = Plant, y = 130, label = paste("p =", p.value)), size = 3)+
  theme_classic() +
  labs(x = "Species",
       y = "Height (cm)")

```

```{r}
gopher_growth_november_mean <- gopher_growth %>% 
  filter(date == "2020-03-01") %>% 
  filter(Plant != "No Plant") %>% 
  mutate(alive = case_when(date_dead %in% c("december2021", "alive") ~ 1,
                           date_dead %in% c("july2020", "november2020") ~ 0)) %>%
  dplyr::select(Plant, height, alive) %>%  
  group_by(Plant, alive) %>% 
  summarise(mean = ci(height, na.rm = TRUE)[1],
            lower = ci(height, na.rm = TRUE)[2],
            upper = ci(height, na.rm = TRUE)[3])

gopher_growth_november_stats <- gopher_growth %>% 
  filter(date == "2020-03-01") %>% 
  filter(Plant != "No Plant") %>% 
  mutate(alive = case_when(date_dead %in% c("december2021", "alive") ~ 1,
                           date_dead %in% c("july2020", "november2020") ~ 0)) %>%
  dplyr::select(Plant, height, alive) %>% 
  nest(data = c(height, alive)) %>% 
  mutate(growth_ttest = map(data, ~tidy(t.test(height~alive, .x)))) %>% 
  unnest(growth_ttest) %>% 
  dplyr::select(Plant, p.value) %>%
  mutate(p.value = round(p.value, digits = 3))%>% 
  full_join(gopher_growth_november_mean, by = "Plant") %>% 
  mutate(community = case_when(Plant %in% c("ADFA", "CEOL", "HEAR", "MALA", "RHOV","SANI") ~ "chaparral",
                               Plant %in% c("ENCA", "HEWH", "SAAP", "SAME") ~ "sage scrub"),
         alive = case_when(alive == 0 ~ "dead",
                           alive == 1 ~ "alive"))
gopher_growth_november_stats$Plant <- factor(gopher_growth_november_stats$Plant, 
                                         levels = c("ADFA", "CEOL", "HEAR", "MALA", "RHOV", "SANI",
                                                    "ENCA", "HEWH", "SAAP","SAME"))

gopher_growth_december_mean <- gopher_growth %>% 
  filter(date == "2020-11-01" & date_dead %in% c("december2021", "alive")) %>% 
  filter(Plant != "No Plant") %>% 
  filter(Plant != "HEAR") %>% 
  filter(Plant != "CEOL") %>% 
  mutate(alive = case_when(date_dead == "december2021" ~ 0,
                           TRUE ~ alive)) %>% 
  dplyr::select(Plant, growth, alive) %>% 
  group_by(Plant, alive) %>% 
  summarise(mean = ci(growth, na.rm = TRUE)[1],
            lower = ci(growth, na.rm = TRUE)[2],
            upper = ci(growth, na.rm = TRUE)[3])

gopher_growth_december_stats <- gopher_growth %>% 
  filter(date == "2020-11-01" & date_dead %in% c("december2021", "alive")) %>% 
  filter(Plant != "No Plant") %>% 
  filter(Plant != "HEAR") %>% 
  filter(Plant != "CEOL") %>% 
  mutate(alive = case_when(date_dead == "december2021" ~ 0,
                           TRUE ~ alive)) %>% 
  dplyr::select(Plant, growth, alive) %>% 
  nest(data = c(growth, alive)) %>% 
  mutate(growth_ttest = map(data, ~tidy(t.test(growth~alive, .x)))) %>% 
  unnest(growth_ttest) %>% 
  dplyr::select(Plant,p.value) %>% 
  mutate(p.value = round(p.value, digits = 3)) %>% 
  full_join(gopher_growth_december_mean, by = "Plant") %>% 
  mutate(community = case_when(Plant %in% c("ADFA", "MALA", "RHOV","SANI") ~ "chaparral",
                               Plant %in% c("ENCA", "HEWH", "SAAP", "SAME") ~ "sage scrub"),
         alive = case_when(alive == 0 ~ "dead",
                           alive == 1 ~ "alive"))
gopher_growth_december_stats$Plant <- factor(gopher_growth_december_stats$Plant, 
                                         levels = c("ADFA", "MALA", "RHOV", "SANI",
                                                    "ENCA", "HEWH", "SAAP","SAME"))

ggplot(gopher_growth_november_stats)+
  geom_point(aes(x = Plant, y = mean, shape = alive, col = community))+
  geom_errorbar(aes(x = Plant, ymin = lower, ymax = upper, col = community)) +
  geom_text(aes(x = Plant, y = 60, label = paste("p =", p.value)), size = 3) +
  theme_classic() +
  labs(x = "Species",
       y = "Growth (cm)")
ggplot(gopher_growth_december_stats)+
  geom_point(aes(x = Plant, y = mean, shape = alive, col = community))+
  geom_errorbar(aes(x = Plant, ymin = lower, ymax = upper, col = community)) +
  geom_text(aes(x = Plant, y = 140, label = paste("p =", p.value)), size = 3)+
  theme_classic() +
  labs(x = "Species",
       y = "Growth (cm)")
```


## Reading in gps points and topgraphy data


```{r}
plots <- st_read(here("data", "plot_gps_points.shp")) %>% 
  rename("plot_number" = "plt_nmb")
elevation <- raster(here("data", "elevation.tif"))
aspect <- raster(here("data", "aspect.tif"))
aspect <- cos((aspect * pi/180) - (225 * pi/180))
slope <- raster(here("data", "slope.tif"))
solar_radiation <- brick(here("data", "sol_rad.tif"))
diurnal_heat <- raster(here("data", "diurnal_heat.tif"))
heat_load <- raster(here("data", "heat_load_index.tif"))
ruggedness_vector <- raster(here("data", "ruggedness_vector.tif"))
sol_rad_aspect <- raster(here("data", "sol_rad_aspect.tif"))
terrain_ruggedness <- raster(here("data", "terrain_ruggedness.tif"))
terrain_texture <- raster(here("data", "terrain_texture.tif"))
topographic_position <- raster(here("data", "topographic_position.tif"))

```


## Extracting topographic data to plot points

```{r}
plots_topography <- plots %>% 
  mutate(elevation = raster::extract(elevation, plots),
         aspect = raster::extract(aspect, plots),
         slope = raster::extract(slope, plots),
         summer_solar_radiation = raster::extract(solar_radiation[[3]], plots),
         spring_solar_radiation = raster::extract(solar_radiation[[2]], plots),
         winter_solar_radiation = raster::extract(solar_radiation[[1]], plots),
         diurnal_heat = raster::extract(diurnal_heat, plots),
         heat_load = raster::extract(heat_load, plots),
         sol_rad_aspect = raster::extract(sol_rad_aspect, plots),
         terrain_ruggedness = raster::extract(terrain_ruggedness, plots),
         terrain_texture = raster::extract(terrain_texture, plots),
         topographic_position = raster::extract(topographic_position, plots)) %>% 
  st_as_sf()
```

## Making shapefiles of survival data for mapping

```{r}
survival_topography_raw <- survival_gopher_raw %>% 
  left_join(plots_topography, by = "plot_number") %>% 
  select(!geometry) %>%
  drop_na() %>%  
  group_by(plot_number) %>% 
  mutate(date_dead = sum(alive)) %>% 
  ungroup() %>% 
  select(!plot_number) %>% 
  mutate(date_dead = case_when(date_dead == 1 ~ "may2020",
                               date_dead == 2 ~ "july2020",
                               date_dead == 3 ~ "november2020",
                               date_dead == 4 ~ "december2021",
                               date_dead == 5 ~ "alive"))

growth_topography_raw <- gopher_growth %>% 
  left_join(plots_topography, by = "plot_number") %>% 
  st_as_sf()
```





