---
title: "Untitled"
author: "Shane Dewees"
date: "2022-09-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(ggfortify)
library(broom)
library(MASS)
library(partykit)
```

```{r}
plant_traits <- read.csv(here("data", "planted_species_traits.csv")) %>% 
  rename(species = Species,
         sla = Specific.Leaf.Area..mm.2.g..1.,
         leaf_water_content = Leaf.Water.Content....,
         ldmc = Leaf.Dry.Matter.Content..LDMC...g.g.,
         leaf_thickness = Leaf.Thickness..mm.,
         leaf_c_n = Leaf.C.N..kg.kg.,
         wue = Integrated.Water.Use.Efficiency..13C.in.ppm.,
         leaf_c_percentage = Leaf.C.Percentage....,
         leaf_n_percentage = Leaf.N.Percentage....,
         leaf_n_area = Leaf.N.Area..g.m2.,
         leaf_n_content_leaf_dry_mass = Leaf.N.Content.Leaf.Dry.Mass..g.N.g.1.DW.,
         leaf_c_area = Leaf.Carbon.Content.Per.Area..kg.C.per.m2.,
         form = Form,
         resprouter = resprouter.,
         seeder = seeder.,
         life_span = max.lifespan..years.,
         altitude_high = Altitude.High..m.,
         south_latitude = Latitude.S..deg.,
         north_latitude = Latitude.N..deg.,
         flowering_season = Flowering.Season,
         flowering_first_month = Flowering.time..1st.month.,
         flowering_last_month = Flowering.time..last.month.,
         flowering_duration = Flowering.Period.Length..d.,
         growth_rate = growth.rate..category.,
         crown_height = Crown.Height..m.,
         max_height = Max.Height..m.,
         crown_width = Crown.Width..m.,
         leaf_persistance = Leaf.persistence,
         petiole_length = Petiole.Length..cm.,
         leaf_lamina_length = Leaf.Lamina.Length..cm.,
         leaf_width = Leaf.Width..cm.,
         dispersal_mechanism = dispersal.mech,
         time_reproduction = Time.to.Reproduction..mo.,
         seed_longevity = Seed.longevity..category.,
         seed_dry_mass = Seed.Dry.Mass..mg.,
         wood_density = Wood.Density.Specific.Gravity..g.cm.3.) %>% 
  dplyr::select(species,
                sla, 
                leaf_water_content, 
                ldmc, 
                leaf_thickness, 
                leaf_c_n, 
                wue, 
                leaf_c_percentage,
                leaf_n_percentage, 
                leaf_n_area, 
                leaf_n_content_leaf_dry_mass, 
                leaf_c_area, 
                form,
                resprouter,
                seeder, 
                life_span, 
                altitude_high, 
                south_latitude, 
                north_latitude, 
                flowering_season, 
                flowering_first_month,
                flowering_last_month, 
                flowering_duration, 
                growth_rate, 
                crown_height, 
                max_height,
                crown_width, 
                leaf_persistance,
                petiole_length, 
                leaf_lamina_length, 
                leaf_width, 
                dispersal_mechanism, 
                time_reproduction, 
                seed_longevity, 
                seed_dry_mass,
                wood_density) 

survival <- read.csv(here("data", "survival.csv")) %>% 
  dplyr::select(!X & !alive) %>% 
  rename(species = Plant)

survival_traits <- survival %>% 
  full_join(plant_traits, by = "species")
```

```{r}
survival_traits_stats <- survival_traits %>% 
  filter(date == "2020-11-01") %>%
  dplyr::select(!species & !date & !resprouter & !seeder & !leaf_persistance) %>% 
  nest(data = c("alive_percent",
                "sla",
                "leaf_water_content",
                "ldmc",
                "leaf_thickness",
                "leaf_c_n",
                "wue",
                "leaf_c_percentage",
                "leaf_n_percentage",
                "leaf_n_area",
                "leaf_n_content_leaf_dry_mass",
                "leaf_c_area",
                "form",
                "life_span",
                "altitude_high",
                "south_latitude",
                "north_latitude",
                "flowering_season",
                "flowering_first_month",
                "flowering_last_month",
                "flowering_duration",
                "growth_rate",
                "crown_height",
                "max_height",
                "crown_width",
                "petiole_length",
                "leaf_lamina_length",
                "leaf_width",
                "dispersal_mechanism",
                "time_reproduction", 
                "seed_longevity",
                "seed_dry_mass",
                "wood_density")) %>% 
  mutate(sla_lm = map(data, ~tidy(lm(alive_percent~sla, .x))),
         leaf_water_content_lm = map(data, ~tidy(lm(alive_percent~leaf_water_content, .x))),
         ldmc_lm = map(data, ~tidy(lm(alive_percent~ldmc, .x))),
         leaf_thickness_lm = map(data, ~tidy(lm(alive_percent~leaf_thickness, .x))),
         leaf_c_n_lm = map(data, ~tidy(lm(alive_percent~leaf_c_n, .x))),
         wue_lm = map(data, ~tidy(lm(alive_percent~wue, .x))),
         leaf_c_percentage_lm = map(data, ~tidy(lm(alive_percent~leaf_c_percentage, .x))),
         leaf_n_percentage_lm = map(data, ~tidy(lm(alive_percent~leaf_n_percentage, .x))),
         leaf_n_area_lm = map(data, ~tidy(lm(alive_percent~leaf_n_area, .x))),
         leaf_n_content_leaf_dry_mass_lm = map(data, ~tidy(lm(alive_percent~leaf_n_content_leaf_dry_mass, .x))),
         leaf_c_area_lm = map(data, ~tidy(lm(alive_percent~leaf_c_area, .x))),
         form_lm = map(data, ~tidy(lm(alive_percent~form, .x))),
         life_span_lm = map(data, ~tidy(lm(alive_percent~life_span, .x))),
         altitude_high_lm = map(data, ~tidy(lm(alive_percent~altitude_high, .x))),
         south_latitude_lm = map(data, ~tidy(lm(alive_percent~south_latitude, .x))),
         north_latitude_lm = map(data, ~tidy(lm(alive_percent~north_latitude, .x))),
         flowering_season_lm = map(data, ~tidy(lm(alive_percent~flowering_season, .x))),
         flowering_first_month_lm = map(data, ~tidy(lm(alive_percent~flowering_first_month, .x))),
         flowering_last_month_lm = map(data, ~tidy(lm(alive_percent~flowering_last_month, .x))),
         flowering_duration_lm = map(data, ~tidy(lm(alive_percent~flowering_duration, .x))),
         growth_rate_lm = map(data, ~tidy(lm(alive_percent~growth_rate, .x))),
         crown_height_lm = map(data, ~tidy(lm(alive_percent~crown_height, .x))),
         max_height_lm = map(data, ~tidy(lm(alive_percent~max_height, .x))),
         crown_width_lm = map(data, ~tidy(lm(alive_percent~crown_width, .x))),
         petiole_length_lm = map(data, ~tidy(lm(alive_percent~petiole_length, .x))),
         leaf_lamina_length_lm = map(data, ~tidy(lm(alive_percent~leaf_lamina_length, .x))),
         leaf_width_lm = map(data, ~tidy(lm(alive_percent~leaf_width, .x))),
         dispersal_mechanism_lm = map(data, ~tidy(lm(alive_percent~dispersal_mechanism, .x))),
         time_reproduction_lm = map(data, ~tidy(lm(alive_percent~time_reproduction, .x))),
         seed_longevity_lm = map(data, ~tidy(lm(alive_percent~seed_longevity, .x))),
         seed_dry_mass_lm = map(data, ~tidy(lm(alive_percent~seed_dry_mass, .x))),
         wood_density_lm = map(data, ~tidy(lm(alive_percent~wood_density, .x)))) %>%
  dplyr::select(!data) %>% 
  unnest(sla_lm) %>% 
  filter(term == "sla") %>% 
  rename(sla_estimate = estimate,
         sla_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_water_content_lm, names_repair = "unique") %>%
    filter(term == "leaf_water_content") %>% 
  rename(lwc_estimate = estimate,
         lwc_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>%
  unnest(ldmc_lm, names_repair = "unique") %>%
  filter(term == "ldmc") %>% 
  rename(ldmc_estimate = estimate,
         ldmc_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_thickness_lm, names_repair = "unique") %>%
  filter(term == "leaf_thickness") %>% 
  rename(leafthickness_estimate = estimate,
         leafthickness_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_c_n_lm, names_repair = "unique") %>%
  filter(term == "leaf_c_n") %>% 
  rename(lcn_estimate = estimate,
         lcn_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(wue_lm, names_repair = "unique") %>%
  filter(term == "wue") %>% 
  rename(wue_estimate = estimate,
         wue_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_c_percentage_lm, names_repair = "unique") %>%
  filter(term == "leaf_c_percentage") %>% 
  rename(lcp_estimate = estimate,
         lcp_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_n_percentage_lm, names_repair = "unique") %>% 
  filter(term == "leaf_n_percentage") %>% 
  rename(lnp_estimate = estimate,
         lnp_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_n_area_lm, names_repair = "unique") %>%
  filter(term == "leaf_n_area") %>% 
  rename(lna_estimate = estimate,
         lna_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_n_content_leaf_dry_mass_lm, names_repair = "unique") %>%
  filter(term == "leaf_n_content_leaf_dry_mass") %>% 
  rename(lncldm_estimate = estimate,
         lncldm_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_c_area_lm, names_repair = "unique") %>%
  filter(term == "leaf_c_area") %>% 
  rename(lca_estimate = estimate,
         lca_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(form_lm, names_repair = "unique") %>%
  filter(term == "form") %>% 
  rename(form_estimate = estimate,
         form_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(life_span_lm, names_repair = "unique") %>%
  filter(term == "life_span") %>% 
  rename(lifespan_estimate = estimate,
         lifespan_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(altitude_high_lm, names_repair = "unique") %>%
  filter(term == "altitude_high") %>% 
  rename(altitudehigh_estimate = estimate,
         altitudehigh_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(south_latitude_lm, names_repair = "unique") %>%
  filter(term == "south_latitude") %>% 
  rename(southlatitude_estimate = estimate,
         southlatitude_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(north_latitude_lm, names_repair = "unique") %>%
  filter(term == "north_latitude") %>% 
  rename(northlatitude_estimate = estimate,
         northlatitude_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_season_lm, names_repair = "unique") %>%
  filter(term == "flowering_season") %>% 
  rename(floweringseason_estimate = estimate,
         floweringseason_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_first_month_lm, names_repair = "unique") %>%
  filter(term == "flowering_first_month") %>% 
  rename(floweringfirstmonth_estimate = estimate,
         floweringfirstmonth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_last_month_lm, names_repair = "unique") %>%
  filter(term == "flowering_last_month") %>% 
  rename(floweringlastmonth_estimate = estimate,
         floweringlastmonth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_duration_lm, names_repair = "unique") %>%
  filter(term == "flowering_duration") %>% 
  rename(floweringduration_estimate = estimate,
         floweringduration_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(growth_rate_lm, names_repair = "unique") %>%
  filter(term == "growth_rate") %>% 
  rename(growthrate_estimate = estimate,
         growthrate_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(crown_height_lm, names_repair = "unique") %>%
  filter(term == "crown_height") %>% 
  rename(crownheight_estimate = estimate,
         crownheight_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(max_height_lm, names_repair = "unique") %>%
  filter(term == "max_height") %>% 
  rename(maxheight_estimate = estimate,
         maxheight_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(crown_width_lm, names_repair = "unique") %>%
  filter(term == "crown_width") %>% 
  rename(crownwidth_estimate = estimate,
         crownwidth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(petiole_length_lm, names_repair = "unique") %>%
  filter(term == "petiole_length") %>% 
  rename(petiolelength_estimate = estimate,
         petiolelength_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_lamina_length_lm, names_repair = "unique") %>%
  filter(term == "leaf_lamina_length") %>% 
  rename(leaflaminalength_estimate = estimate,
         leaflaminalength_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_width_lm, names_repair = "unique") %>%
  filter(term == "leaf_width") %>% 
  rename(leafwidth_estimate = estimate,
         leafwidth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(dispersal_mechanism_lm, names_repair = "unique") %>%
  filter(term == "dispersal_mechanism") %>% 
  rename(dispersal_estimate = estimate,
         dispersal_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(time_reproduction_lm, names_repair = "unique") %>%
  filter(term == "time_reproduction") %>% 
  rename(timereproduction_estimate = estimate,
         timereproduction_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(seed_longevity_lm, names_repair = "unique") %>%
  filter(term == "seed_longevity") %>% 
  rename(seedlongevity_estimate = estimate,
         seedlongevity_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(seed_dry_mass_lm, names_repair = "unique") %>%
  filter(term == "seed_dry_mass") %>% 
  rename(seeddrymass_estimate = estimate,
         seeddrymass_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(wood_density_lm, names_repair = "unique") %>% 
  filter(term == "wood_density") %>% 
  rename(wooddensity_estimate = estimate,
         wooddensity_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  pivot_longer(cols = 1:64, names_to = "names", values_to = "values") %>% 
  separate(names, into = c("variables", "stats"), sep = "_") %>% 
  pivot_wider(names_from = "stats", values_from = "values") %>% 
  filter(p < 0.05)
  

ggplot(survival_traits %>% filter(date == "2020-11-01"), aes(x = crown_width, y = alive_percent))+
  geom_text(aes(label = species)) +
  geom_smooth(method = "lm") +
  theme_classic()

ggplot(survival_traits %>% filter(date == "2020-11-01"), aes(x = petiole_length, y = alive_percent)) +
  geom_text(aes(label = species)) +
  geom_smooth(method = "lm") +
  theme_classic()
```

```{r}
plant_traits_trimmed <- plant_traits %>% 
  dplyr::select(species,
         sla,
         leaf_water_content,
         ldmc,
         leaf_thickness,
         leaf_c_n,
         wue,
         leaf_c_percentage,
         leaf_n_percentage,
         leaf_n_area,
         leaf_n_content_leaf_dry_mass,
         leaf_c_area,
         growth_rate,
         crown_height,
         max_height,
         crown_width,
         petiole_length,
         leaf_lamina_length,
         leaf_width,
         wood_density)

traits_trimmed_pca_input <- plant_traits_trimmed %>% 
  column_to_rownames(var = "species")

traits_trimmed_pca <- traits_trimmed_pca_input %>% 
  prcomp(center = TRUE, scale. = TRUE)
summary(traits_trimmed_pca)

pca_trimmed <- as.data.frame(traits_trimmed_pca[["x"]]) %>% 
  rownames_to_column(var = "species")

survival_pca_trimmed <- survival %>% 
  full_join(pca_trimmed, by = "species")

survival_pca_trimmed_stats <- survival_pca_trimmed %>% 
  filter(date == "2020-11-01") %>% 
  dplyr::select(!species & !date) %>% 
  nest(data = c(alive_percent,
                PC1,
                PC2,
                PC3,
                PC4,
                PC5,
                PC6,
                PC7,
                PC8,
                PC9,
                PC10)) %>% 
  mutate(pc1_lm = map(data, ~tidy(lm(alive_percent~PC1, .x))),
         pc2_lm = map(data, ~tidy(lm(alive_percent~PC2, .x))),
         pc3_lm = map(data, ~tidy(lm(alive_percent~PC3, .x))),
         pc4_lm = map(data, ~tidy(lm(alive_percent~PC4, .x))),
         pc5_lm = map(data, ~tidy(lm(alive_percent~PC5, .x))),
         pc6_lm = map(data, ~tidy(lm(alive_percent~PC6, .x))),
         pc7_lm = map(data, ~tidy(lm(alive_percent~PC7, .x))),
         pc8_lm = map(data, ~tidy(lm(alive_percent~PC8, .x))),
         pc9_lm = map(data, ~tidy(lm(alive_percent~PC9, .x))),
         pc10_lm = map(data, ~tidy(lm(alive_percent~PC10, .x)))) %>% 
  dplyr::select(!data) %>% 
  unnest(pc1_lm) %>% 
  filter(term == "PC1") %>% 
  rename(pc1_estimate = estimate,
         pc1_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(pc2_lm) %>% 
  filter(term == "PC2") %>% 
  rename(pc2_estimate = estimate,
         pc2_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(pc3_lm) %>% 
  filter(term == "PC3") %>% 
  rename(pc3_estimate = estimate,
         pc3_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(pc4_lm) %>% 
  filter(term == "PC4") %>% 
  rename(pc4_estimate = estimate,
         pc4_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(pc5_lm) %>% 
  filter(term == "PC5") %>% 
  rename(pc5_estimate = estimate,
         pc5_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(pc6_lm) %>% 
  filter(term == "PC6") %>% 
  rename(pc6_estimate = estimate,
         pc6_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(pc7_lm) %>% 
  filter(term == "PC7") %>% 
  rename(pc7_estimate = estimate,
         pc7_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(pc8_lm) %>% 
  filter(term == "PC8") %>% 
  rename(pc8_estimate = estimate,
         pc8_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(pc9_lm) %>% 
  filter(term == "PC9") %>% 
  rename(pc9_estimate = estimate,
         pc9_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(pc10_lm) %>% 
  filter(term == "PC10") %>% 
  rename(pc10_estimate = estimate,
         pc10_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  pivot_longer(cols = 1:20, names_to = "names", values_to = "values") %>% 
  separate(col = names, into = c("variables", "stats"), sep = "_") %>% 
  pivot_wider(names_from = "stats", values_from = "values") 
  
ggplot(survival_pca_trimmed %>%  filter(date == "2020-11-01"), aes(x = PC2, y = PC1)) +
  geom_text(aes(label = species))+
   geom_hline(yintercept = 0, linetype = "dashed")+
  geom_vline(xintercept = 0, linetype = "dashed")+
  theme_classic()
ggplot(survival_pca_trimmed %>% filter(date == "2020-11-01"), aes(x = PC1, y = alive_percent))+
  geom_text(aes(label = species))+
  geom_smooth(method = "lm") +
  theme_classic()
ggplot(survival_pca_trimmed %>% filter(date == "2020-11-01"), aes(x = PC2, y = alive_percent))+
  geom_text(aes(label = species))+
  geom_smooth(method = "lm") +
  theme_classic()

traits_pc2_model <- lm(alive_percent~PC2, data = survival_pca_trimmed %>% filter(date == "2020-11-01"))
autoplot(traits_pc2_model)

barplot(traits_trimmed_pca$rotation[,1], las = 2)
barplot(traits_trimmed_pca$rotation[,2], las = 2)
```

```{r}
planting_topography_pca_data <- planting_topography_pca_data %>%
  filter(alive == "alive") %>% 
  mutate(species = case_when(Plant == "ADFA" ~ "Adenostoma fasciculatum",
                             Plant == "CEOL" ~ "Ceanothus oliganthus",
                             Plant == "ENCA" ~ "Encelia californica",
                             Plant == "HEAR" ~ "Heteromeles arbutifolia",
                             Plant == "HEWH" ~ "Hesperoyucca whipplei",
                             Plant == "MALA" ~ "Malosma laurina",
                             Plant == "RHOV" ~ "Rhus ovata",
                             Plant == "SAAP" ~ "Salvia apiana",
                             Plant == "SAME" ~ "Salvia mellifera",
                             Plant == "SANI" ~ "Sambucus nigra")) %>% 
  rename(topography_pc1_mean = pc1_mean, 
         topography_pc6_mean = pc6_mean)

combined_pca <- planting_topography_pca_data %>% 
  full_join(survival_pca_trimmed, by = "species") %>% 
  filter(date == "2020-11-01") %>% 
  dplyr::select(species, 
                topography_pc1_mean,
                topography_pc6_mean,
                PC1,
                PC2)
combined_pca_stats <- combined_pca %>% 
  ungroup() %>% 
  dplyr::select(!species & !Plant) %>% 
  nest(data = c(topography_pc1_mean,
                topography_pc6_mean,
                PC1,
                PC2)) %>% 
  mutate(pc1_lm = map(data, ~tidy(lm(topography_pc1_mean~PC2, .x))),
         pc6_lm = map(data, ~tidy(lm(topography_pc6_mean~PC2, .x))))

summary(lm(topography_pc6_mean~PC1, combined_pca))
summary(lm(topography_pc6_mean~PC2, combined_pca))
summary(lm(topography_pc6_mean~PC1+PC2, combined_pca))
summary(lm(topography_pc6_mean~PC1*PC2, combined_pca))

ggplot(combined_pca, aes(x = PC1, y = topography_pc6_mean))+
  geom_text(aes(label = species))+
  geom_smooth(method = "lm")
  
```






```{r}
survival_traits_pc <- survival_traits %>% 
  filter(date == "2020-11-01") %>%
  dplyr::select(!date & !resprouter & !seeder & !leaf_persistance) %>% 
  left_join(planting_topography_pca_data, by = "species") %>% 
  dplyr::select(!pc2_mean & !pc3_mean & !pc4_mean & !pc5_mean & !Plant & !alive_percent & !alive)

survival_traits_pc1_stats <-  survival_traits_pc%>% 
  nest(data = c("species",
                "topography_pc1_mean",
                "topography_pc6_mean",
                "sla",
                "leaf_water_content",
                "ldmc",
                "leaf_thickness",
                "leaf_c_n",
                "wue",
                "leaf_c_percentage",
                "leaf_n_percentage",
                "leaf_n_area",
                "leaf_n_content_leaf_dry_mass",
                "leaf_c_area",
                "form",
                "life_span",
                "altitude_high",
                "south_latitude",
                "north_latitude",
                "flowering_season",
                "flowering_first_month",
                "flowering_last_month",
                "flowering_duration",
                "growth_rate",
                "crown_height",
                "max_height",
                "crown_width",
                "petiole_length",
                "leaf_lamina_length",
                "leaf_width",
                "dispersal_mechanism",
                "time_reproduction", 
                "seed_longevity",
                "seed_dry_mass",
                "wood_density")) %>%  
  mutate(sla_lm = map(data, ~tidy(lm(topography_pc1_mean~sla, .x))),
         leaf_water_content_lm = map(data, ~tidy(lm(topography_pc1_mean~leaf_water_content, .x))),
         ldmc_lm = map(data, ~tidy(lm(topography_pc1_mean~ldmc, .x))),
         leaf_thickness_lm = map(data, ~tidy(lm(topography_pc1_mean~leaf_thickness, .x))),
         leaf_c_n_lm = map(data, ~tidy(lm(topography_pc1_mean~leaf_c_n, .x))),
         wue_lm = map(data, ~tidy(lm(topography_pc1_mean~wue, .x))),
         leaf_c_percentage_lm = map(data, ~tidy(lm(topography_pc1_mean~leaf_c_percentage, .x))),
         leaf_n_percentage_lm = map(data, ~tidy(lm(topography_pc1_mean~leaf_n_percentage, .x))),
         leaf_n_area_lm = map(data, ~tidy(lm(topography_pc1_mean~leaf_n_area, .x))),
         leaf_n_content_leaf_dry_mass_lm = map(data, ~tidy(lm(topography_pc1_mean~leaf_n_content_leaf_dry_mass, .x))),
         leaf_c_area_lm = map(data, ~tidy(lm(topography_pc1_mean~leaf_c_area, .x))),
         form_lm = map(data, ~tidy(lm(topography_pc1_mean~form, .x))),
         life_span_lm = map(data, ~tidy(lm(topography_pc1_mean~life_span, .x))),
         altitude_high_lm = map(data, ~tidy(lm(topography_pc1_mean~altitude_high, .x))),
         south_latitude_lm = map(data, ~tidy(lm(topography_pc1_mean~south_latitude, .x))),
         north_latitude_lm = map(data, ~tidy(lm(topography_pc1_mean~north_latitude, .x))),
         flowering_season_lm = map(data, ~tidy(lm(topography_pc1_mean~flowering_season, .x))),
         flowering_first_month_lm = map(data, ~tidy(lm(topography_pc1_mean~flowering_first_month, .x))),
         flowering_last_month_lm = map(data, ~tidy(lm(topography_pc1_mean~flowering_last_month, .x))),
         flowering_duration_lm = map(data, ~tidy(lm(topography_pc1_mean~flowering_duration, .x))),
         growth_rate_lm = map(data, ~tidy(lm(topography_pc1_mean~growth_rate, .x))),
         crown_height_lm = map(data, ~tidy(lm(topography_pc1_mean~crown_height, .x))),
         max_height_lm = map(data, ~tidy(lm(topography_pc1_mean~max_height, .x))),
         crown_width_lm = map(data, ~tidy(lm(topography_pc1_mean~crown_width, .x))),
         petiole_length_lm = map(data, ~tidy(lm(topography_pc1_mean~petiole_length, .x))),
         leaf_lamina_length_lm = map(data, ~tidy(lm(topography_pc1_mean~leaf_lamina_length, .x))),
         leaf_width_lm = map(data, ~tidy(lm(topography_pc1_mean~leaf_width, .x))),
         dispersal_mechanism_lm = map(data, ~tidy(lm(topography_pc1_mean~dispersal_mechanism, .x))),
         time_reproduction_lm = map(data, ~tidy(lm(topography_pc1_mean~time_reproduction, .x))),
         seed_longevity_lm = map(data, ~tidy(lm(topography_pc1_mean~seed_longevity, .x))),
         seed_dry_mass_lm = map(data, ~tidy(lm(topography_pc1_mean~seed_dry_mass, .x))),
         wood_density_lm = map(data, ~tidy(lm(topography_pc1_mean~wood_density, .x)))) %>%
  dplyr::select(!data) %>% 
  unnest(sla_lm) %>% 
  filter(term == "sla") %>% 
  rename(sla_estimate = estimate,
         sla_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_water_content_lm, names_repair = "unique") %>%
    filter(term == "leaf_water_content") %>% 
  rename(lwc_estimate = estimate,
         lwc_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>%
  unnest(ldmc_lm, names_repair = "unique") %>%
  filter(term == "ldmc") %>% 
  rename(ldmc_estimate = estimate,
         ldmc_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_thickness_lm, names_repair = "unique") %>%
  filter(term == "leaf_thickness") %>% 
  rename(leafthickness_estimate = estimate,
         leafthickness_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_c_n_lm, names_repair = "unique") %>%
  filter(term == "leaf_c_n") %>% 
  rename(lcn_estimate = estimate,
         lcn_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(wue_lm, names_repair = "unique") %>%
  filter(term == "wue") %>% 
  rename(wue_estimate = estimate,
         wue_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_c_percentage_lm, names_repair = "unique") %>%
  filter(term == "leaf_c_percentage") %>% 
  rename(lcp_estimate = estimate,
         lcp_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_n_percentage_lm, names_repair = "unique") %>% 
  filter(term == "leaf_n_percentage") %>% 
  rename(lnp_estimate = estimate,
         lnp_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_n_area_lm, names_repair = "unique") %>%
  filter(term == "leaf_n_area") %>% 
  rename(lna_estimate = estimate,
         lna_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_n_content_leaf_dry_mass_lm, names_repair = "unique") %>%
  filter(term == "leaf_n_content_leaf_dry_mass") %>% 
  rename(lncldm_estimate = estimate,
         lncldm_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_c_area_lm, names_repair = "unique") %>%
  filter(term == "leaf_c_area") %>% 
  rename(lca_estimate = estimate,
         lca_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(form_lm, names_repair = "unique") %>%
  filter(term == "form") %>% 
  rename(form_estimate = estimate,
         form_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(life_span_lm, names_repair = "unique") %>%
  filter(term == "life_span") %>% 
  rename(lifespan_estimate = estimate,
         lifespan_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(altitude_high_lm, names_repair = "unique") %>%
  filter(term == "altitude_high") %>% 
  rename(altitudehigh_estimate = estimate,
         altitudehigh_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(south_latitude_lm, names_repair = "unique") %>%
  filter(term == "south_latitude") %>% 
  rename(southlatitude_estimate = estimate,
         southlatitude_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(north_latitude_lm, names_repair = "unique") %>%
  filter(term == "north_latitude") %>% 
  rename(northlatitude_estimate = estimate,
         northlatitude_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_season_lm, names_repair = "unique") %>%
  filter(term == "flowering_season") %>% 
  rename(floweringseason_estimate = estimate,
         floweringseason_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_first_month_lm, names_repair = "unique") %>%
  filter(term == "flowering_first_month") %>% 
  rename(floweringfirstmonth_estimate = estimate,
         floweringfirstmonth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_last_month_lm, names_repair = "unique") %>%
  filter(term == "flowering_last_month") %>% 
  rename(floweringlastmonth_estimate = estimate,
         floweringlastmonth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_duration_lm, names_repair = "unique") %>%
  filter(term == "flowering_duration") %>% 
  rename(floweringduration_estimate = estimate,
         floweringduration_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(growth_rate_lm, names_repair = "unique") %>%
  filter(term == "growth_rate") %>% 
  rename(growthrate_estimate = estimate,
         growthrate_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(crown_height_lm, names_repair = "unique") %>%
  filter(term == "crown_height") %>% 
  rename(crownheight_estimate = estimate,
         crownheight_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(max_height_lm, names_repair = "unique") %>%
  filter(term == "max_height") %>% 
  rename(maxheight_estimate = estimate,
         maxheight_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(crown_width_lm, names_repair = "unique") %>%
  filter(term == "crown_width") %>% 
  rename(crownwidth_estimate = estimate,
         crownwidth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(petiole_length_lm, names_repair = "unique") %>%
  filter(term == "petiole_length") %>% 
  rename(petiolelength_estimate = estimate,
         petiolelength_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_lamina_length_lm, names_repair = "unique") %>%
  filter(term == "leaf_lamina_length") %>% 
  rename(leaflaminalength_estimate = estimate,
         leaflaminalength_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_width_lm, names_repair = "unique") %>%
  filter(term == "leaf_width") %>% 
  rename(leafwidth_estimate = estimate,
         leafwidth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(dispersal_mechanism_lm, names_repair = "unique") %>%
  filter(term == "dispersal_mechanism") %>% 
  rename(dispersal_estimate = estimate,
         dispersal_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(time_reproduction_lm, names_repair = "unique") %>%
  filter(term == "time_reproduction") %>% 
  rename(timereproduction_estimate = estimate,
         timereproduction_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(seed_longevity_lm, names_repair = "unique") %>%
  filter(term == "seed_longevity") %>% 
  rename(seedlongevity_estimate = estimate,
         seedlongevity_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(seed_dry_mass_lm, names_repair = "unique") %>%
  filter(term == "seed_dry_mass") %>% 
  rename(seeddrymass_estimate = estimate,
         seeddrymass_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(wood_density_lm, names_repair = "unique") %>% 
  filter(term == "wood_density") %>% 
  rename(wooddensity_estimate = estimate,
         wooddensity_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  pivot_longer(cols = 1:64, names_to = "names", values_to = "values") %>% 
  separate(names, into = c("variables", "stats"), sep = "_") %>% 
  pivot_wider(names_from = "stats", values_from = "values") %>% 
  filter(p < 0.05)
  

ggplot(survival_traits_pc, aes(x = leaf_n_area, y = topography_pc1_mean))+
  geom_text(aes(label = species)) +
  geom_smooth(method = "lm") +
  theme_classic()

ggplot(survival_traits_pc, aes(x = life_span, y = topography_pc1_mean))+
  geom_text(aes(label = species)) +
  geom_smooth(method = "lm") +
  theme_classic()

ggplot(survival_traits_pc, aes(x = time_reproduction, y = topography_pc1_mean))+
  geom_text(aes(label = species)) +
  geom_smooth(method = "lm") +
  theme_classic()
```

```{r}
survival_traits_pc6 <- survival_traits %>% 
  filter(date == "2020-11-01") %>%
  dplyr::select(!date & !resprouter & !seeder & !leaf_persistance) %>% 
  left_join(planting_topography_pca_data, by = "species") %>% 
  dplyr::select(!pc2_mean & !pc3_mean & !pc4_mean & !pc5_mean & !Plant & !alive_percent & !alive) %>% 
  nest(data = c("species",
                "topography_pc1_mean",
                "topography_pc6_mean",
                "sla",
                "leaf_water_content",
                "ldmc",
                "leaf_thickness",
                "leaf_c_n",
                "wue",
                "leaf_c_percentage",
                "leaf_n_percentage",
                "leaf_n_area",
                "leaf_n_content_leaf_dry_mass",
                "leaf_c_area",
                "form",
                "life_span",
                "altitude_high",
                "south_latitude",
                "north_latitude",
                "flowering_season",
                "flowering_first_month",
                "flowering_last_month",
                "flowering_duration",
                "growth_rate",
                "crown_height",
                "max_height",
                "crown_width",
                "petiole_length",
                "leaf_lamina_length",
                "leaf_width",
                "dispersal_mechanism",
                "time_reproduction", 
                "seed_longevity",
                "seed_dry_mass",
                "wood_density")) %>%  
  mutate(sla_lm = map(data, ~tidy(lm(topography_pc6_mean~sla, .x))),
         leaf_water_content_lm = map(data, ~tidy(lm(topography_pc6_mean~leaf_water_content, .x))),
         ldmc_lm = map(data, ~tidy(lm(topography_pc6_mean~ldmc, .x))),
         leaf_thickness_lm = map(data, ~tidy(lm(topography_pc6_mean~leaf_thickness, .x))),
         leaf_c_n_lm = map(data, ~tidy(lm(topography_pc6_mean~leaf_c_n, .x))),
         wue_lm = map(data, ~tidy(lm(topography_pc6_mean~wue, .x))),
         leaf_c_percentage_lm = map(data, ~tidy(lm(topography_pc6_mean~leaf_c_percentage, .x))),
         leaf_n_percentage_lm = map(data, ~tidy(lm(topography_pc6_mean~leaf_n_percentage, .x))),
         leaf_n_area_lm = map(data, ~tidy(lm(topography_pc6_mean~leaf_n_area, .x))),
         leaf_n_content_leaf_dry_mass_lm = map(data, ~tidy(lm(topography_pc6_mean~leaf_n_content_leaf_dry_mass, .x))),
         leaf_c_area_lm = map(data, ~tidy(lm(topography_pc6_mean~leaf_c_area, .x))),
         form_lm = map(data, ~tidy(lm(topography_pc6_mean~form, .x))),
         life_span_lm = map(data, ~tidy(lm(topography_pc6_mean~life_span, .x))),
         altitude_high_lm = map(data, ~tidy(lm(topography_pc6_mean~altitude_high, .x))),
         south_latitude_lm = map(data, ~tidy(lm(topography_pc6_mean~south_latitude, .x))),
         north_latitude_lm = map(data, ~tidy(lm(topography_pc6_mean~north_latitude, .x))),
         flowering_season_lm = map(data, ~tidy(lm(topography_pc6_mean~flowering_season, .x))),
         flowering_first_month_lm = map(data, ~tidy(lm(topography_pc6_mean~flowering_first_month, .x))),
         flowering_last_month_lm = map(data, ~tidy(lm(topography_pc6_mean~flowering_last_month, .x))),
         flowering_duration_lm = map(data, ~tidy(lm(topography_pc6_mean~flowering_duration, .x))),
         growth_rate_lm = map(data, ~tidy(lm(topography_pc6_mean~growth_rate, .x))),
         crown_height_lm = map(data, ~tidy(lm(topography_pc6_mean~crown_height, .x))),
         max_height_lm = map(data, ~tidy(lm(topography_pc6_mean~max_height, .x))),
         crown_width_lm = map(data, ~tidy(lm(topography_pc6_mean~crown_width, .x))),
         petiole_length_lm = map(data, ~tidy(lm(topography_pc6_mean~petiole_length, .x))),
         leaf_lamina_length_lm = map(data, ~tidy(lm(topography_pc6_mean~leaf_lamina_length, .x))),
         leaf_width_lm = map(data, ~tidy(lm(topography_pc6_mean~leaf_width, .x))),
         dispersal_mechanism_lm = map(data, ~tidy(lm(topography_pc6_mean~dispersal_mechanism, .x))),
         time_reproduction_lm = map(data, ~tidy(lm(topography_pc6_mean~time_reproduction, .x))),
         seed_longevity_lm = map(data, ~tidy(lm(topography_pc6_mean~seed_longevity, .x))),
         seed_dry_mass_lm = map(data, ~tidy(lm(topography_pc6_mean~seed_dry_mass, .x))),
         wood_density_lm = map(data, ~tidy(lm(topography_pc6_mean~wood_density, .x)))) %>%
  dplyr::select(!data) %>% 
  unnest(sla_lm) %>% 
  filter(term == "sla") %>% 
  rename(sla_estimate = estimate,
         sla_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_water_content_lm, names_repair = "unique") %>%
    filter(term == "leaf_water_content") %>% 
  rename(lwc_estimate = estimate,
         lwc_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>%
  unnest(ldmc_lm, names_repair = "unique") %>%
  filter(term == "ldmc") %>% 
  rename(ldmc_estimate = estimate,
         ldmc_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_thickness_lm, names_repair = "unique") %>%
  filter(term == "leaf_thickness") %>% 
  rename(leafthickness_estimate = estimate,
         leafthickness_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_c_n_lm, names_repair = "unique") %>%
  filter(term == "leaf_c_n") %>% 
  rename(lcn_estimate = estimate,
         lcn_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(wue_lm, names_repair = "unique") %>%
  filter(term == "wue") %>% 
  rename(wue_estimate = estimate,
         wue_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_c_percentage_lm, names_repair = "unique") %>%
  filter(term == "leaf_c_percentage") %>% 
  rename(lcp_estimate = estimate,
         lcp_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_n_percentage_lm, names_repair = "unique") %>% 
  filter(term == "leaf_n_percentage") %>% 
  rename(lnp_estimate = estimate,
         lnp_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_n_area_lm, names_repair = "unique") %>%
  filter(term == "leaf_n_area") %>% 
  rename(lna_estimate = estimate,
         lna_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_n_content_leaf_dry_mass_lm, names_repair = "unique") %>%
  filter(term == "leaf_n_content_leaf_dry_mass") %>% 
  rename(lncldm_estimate = estimate,
         lncldm_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_c_area_lm, names_repair = "unique") %>%
  filter(term == "leaf_c_area") %>% 
  rename(lca_estimate = estimate,
         lca_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(form_lm, names_repair = "unique") %>%
  filter(term == "form") %>% 
  rename(form_estimate = estimate,
         form_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(life_span_lm, names_repair = "unique") %>%
  filter(term == "life_span") %>% 
  rename(lifespan_estimate = estimate,
         lifespan_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(altitude_high_lm, names_repair = "unique") %>%
  filter(term == "altitude_high") %>% 
  rename(altitudehigh_estimate = estimate,
         altitudehigh_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(south_latitude_lm, names_repair = "unique") %>%
  filter(term == "south_latitude") %>% 
  rename(southlatitude_estimate = estimate,
         southlatitude_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(north_latitude_lm, names_repair = "unique") %>%
  filter(term == "north_latitude") %>% 
  rename(northlatitude_estimate = estimate,
         northlatitude_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_season_lm, names_repair = "unique") %>%
  filter(term == "flowering_season") %>% 
  rename(floweringseason_estimate = estimate,
         floweringseason_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_first_month_lm, names_repair = "unique") %>%
  filter(term == "flowering_first_month") %>% 
  rename(floweringfirstmonth_estimate = estimate,
         floweringfirstmonth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_last_month_lm, names_repair = "unique") %>%
  filter(term == "flowering_last_month") %>% 
  rename(floweringlastmonth_estimate = estimate,
         floweringlastmonth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(flowering_duration_lm, names_repair = "unique") %>%
  filter(term == "flowering_duration") %>% 
  rename(floweringduration_estimate = estimate,
         floweringduration_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(growth_rate_lm, names_repair = "unique") %>%
  filter(term == "growth_rate") %>% 
  rename(growthrate_estimate = estimate,
         growthrate_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(crown_height_lm, names_repair = "unique") %>%
  filter(term == "crown_height") %>% 
  rename(crownheight_estimate = estimate,
         crownheight_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(max_height_lm, names_repair = "unique") %>%
  filter(term == "max_height") %>% 
  rename(maxheight_estimate = estimate,
         maxheight_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(crown_width_lm, names_repair = "unique") %>%
  filter(term == "crown_width") %>% 
  rename(crownwidth_estimate = estimate,
         crownwidth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(petiole_length_lm, names_repair = "unique") %>%
  filter(term == "petiole_length") %>% 
  rename(petiolelength_estimate = estimate,
         petiolelength_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_lamina_length_lm, names_repair = "unique") %>%
  filter(term == "leaf_lamina_length") %>% 
  rename(leaflaminalength_estimate = estimate,
         leaflaminalength_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(leaf_width_lm, names_repair = "unique") %>%
  filter(term == "leaf_width") %>% 
  rename(leafwidth_estimate = estimate,
         leafwidth_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(dispersal_mechanism_lm, names_repair = "unique") %>%
  filter(term == "dispersal_mechanism") %>% 
  rename(dispersal_estimate = estimate,
         dispersal_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(time_reproduction_lm, names_repair = "unique") %>%
  filter(term == "time_reproduction") %>% 
  rename(timereproduction_estimate = estimate,
         timereproduction_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(seed_longevity_lm, names_repair = "unique") %>%
  filter(term == "seed_longevity") %>% 
  rename(seedlongevity_estimate = estimate,
         seedlongevity_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(seed_dry_mass_lm, names_repair = "unique") %>%
  filter(term == "seed_dry_mass") %>% 
  rename(seeddrymass_estimate = estimate,
         seeddrymass_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  unnest(wood_density_lm, names_repair = "unique") %>% 
  filter(term == "wood_density") %>% 
  rename(wooddensity_estimate = estimate,
         wooddensity_p = p.value) %>% 
  dplyr::select(!term & !std.error & !statistic) %>% 
  pivot_longer(cols = 1:64, names_to = "names", values_to = "values") %>% 
  separate(names, into = c("variables", "stats"), sep = "_") %>% 
  pivot_wider(names_from = "stats", values_from = "values") %>% 
  filter(p < 0.05)

ggplot(survival_traits_pc, aes(x = leaf_c_area, y = topography_pc6_mean))+
  geom_text(aes(label = species)) +
  geom_smooth(method = "lm") +
  theme_classic()

ggplot(survival_traits_pc, aes(x = leaf_n_percentage, y = topography_pc6_mean))+
  geom_text(aes(label = species)) +
  geom_smooth(method = "lm") +
  theme_classic()

ggplot(survival_traits_pc, aes(x = leaf_n_content_leaf_dry_mass, y = topography_pc6_mean))+
  geom_text(aes(label = species)) +
  geom_smooth(method = "lm") +
  theme_classic()

ggplot(survival_traits_pc, aes(x = leaf_c_area, y = topography_pc6_mean))+
  geom_text(aes(label = species)) +
  geom_smooth(method = "lm") +
  theme_classic()

ggplot(survival_traits_pc, aes(x = south_latitude, y = topography_pc6_mean))+
  geom_text(aes(label = species)) +
  geom_smooth(method = "lm") +
  theme_classic()

ggplot(survival_traits_pc, aes(x = flowering_duration, y = topography_pc6_mean))+
  geom_text(aes(label = species)) +
  geom_smooth(method = "lm") +
  theme_classic()
```

